// Voyager's safety and liability notice, Irish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerGa = '''
Is deais turgnamhach foinse oscailte é Voyager do charr, arna chothabháil ag an bpobal. Cuireann sé loingseoireacht atá bunaithe ar shonraí OpenStreetMap agus ar phrótacal Nostr le chéile le seinm meán, faisnéis aimsire, sintéis chainte agus feidhmeanna teileafóin roghnacha. Ach an feidhmchlár seo a íoslódáil, a shuiteáil nó a úsáid, glacann an t-úsáideoir gan choinníoll leis na téarmaí seo a leanas go léir, gan teorainn chríche:

🚗  SÁBHÁILTEACHT AR BHÓITHRE AR DTÚS
Ní mór don tiománaí a shúile a choinneáil ar an mbóthar i gcónaí agus gach riail tráchta agus comharthaíocht atá i bhfeidhm a chomhlíonadh; tá tosaíocht acu sin i gcónaí ar aon treoir ón bhfeidhmchlár. Ná hoibrigh an gléas agus tú ag tiomáint riamh; daingnigh i ngreamán faofa infheicthe é sula dtosaíonn tú ag taisteal, agus ná bain d'aird den bhóthar riamh chun idirghníomhú leis agus an fheithicil ag gluaiseacht. I go leor dlínsí is cion ann féin é gléas a láimhseáil taobh thiar den roth stiúrtha, is cuma cad atá ar taispeáint air.

🎵  MEÁIN AGUS TEILEAFÓNAÍOCHT AGUS TÚ AG TIOMÁINT
Is áiseanna caoithiúlachta iad seinm ceoil, léamh teachtaireachtaí os ard agus láimhseáil glaonna, agus cuirtear ar fáil iad ar na téarmaí céanna le gach rud eile san fheidhmchlár. Is ualaí cognaíocha iad ceol a roghnú, leabharlann a bhrabhsáil, teachtaireacht a léamh ar an scáileán nó comhrá a dhéanamh, agus laghdaíonn siad cumas tiomána. Socraigh an seinm sula dtosaíonn tú ag taisteal agus úsáid na rialtáin fhisiciúla ar an roth stiúrtha in ionad an scáileáin tadhaill nuair atá an fheithicil ag gluaiseacht. Nuair a chuireann an dlí áitiúil srian nó cosc ar úsáid teileafóin agus duine ag tiomáint, tá tosaíocht ag an dlí sin agus ní ceadmhach na feidhmeanna comhfhreagracha a úsáid.

⚠️  GLACADH LE RIOSCA — AR FUD AN DOMHAIN
Ach Voyager a úsáid, in aon tír agus faoi aon chóras dlí, glacann an t-úsáideoir go feasach agus go deonach le GACH riosca a bhaineann lena úsáid, lena n-áirítear ach gan a bheith teoranta do: timpistí bóthair, díobháil phearsanta, bás, damáiste do mhaoin, damáiste don fheithicil, fíneálacha, pionóis riaracháin, tarraingt chun siúil, coinneáil feithicle, dliteanas coiriúil, nó aon iarmhairt eile a eascraíonn go díreach nó go hindíreach as brath ar an bhfeidhmchlár. Is é an t-úsáideoir amháin atá freagrach go hiomlán as gach cinneadh tiomána agus loingseoireachta.

🚫  GAN BARÁNTAS
Cuirtear Voyager ar fáil go docht "MAR ATÁ" agus "MAR ATÁ AR FÁIL", gan bharántas ar bith, sainráite, intuigthe nó reachtúil — lena n-áirítear, gan teorainn, barántais chruinnis, iomláine, iontaofachta, infhaighteachta, indíoltachta, oiriúnachta chun críche ar leith agus neamhshárú ceart. Tagann sonraí léarscáile, bealaí, teorainneacha luais, ceamaraí luais agus faisnéis faoi chriosanna trácht srianta ó fhoinsí oscailte a chothaíonn an pobal (OpenStreetMap, Overpass API), agus d'fhéadfaidís a bheith neamhiomlán, as dáta nó míchruinn d'aon tír, réigiún nó ceantar, tráth ar bith agus gan fógra. Is ar an úsáideoir amháin atá an fhreagracht a dheimhniú go neamhspleách, roimh an turas agus lena linn, an bhfuil aon bhealach molta dleathach agus inúsáidte i gcomparáid leis an gcomharthaíocht agus na rialacháin áitiúla oifigiúla.

📍  CRUINNEAS AGUS GPS
D'fhéadfadh suíomhú GPS a bheith míchruinn nó gan a bheith ar fáil. Ní chuirtear treoracha, achair agus foláirimh ar fáil ach mar threoir amháin agus níor cheart go mbeidís riamh mar an t-aon bhunús le cinneadh tiomána.

🛡️  TEORANNÚ DLITEANAIS
A mhéid a cheadaíonn an dlí is infheidhme in aon dlínse, ní bheidh na forbróirí, na rannpháirtithe ná aon pháirtí a bhfuil baint aige le cruthú nó dáileadh Voyager faoi dhliteanas i leith aon damáistí díreacha, indíreacha, teagmhasacha, iarmhartacha, speisialta, eiseamláireacha nó pionósacha de chineál ar bith — lena n-áirítear díobháil phearsanta, bás nó caillteanas airgeadais — a eascraíonn as úsáid an fheidhmchláir nó as neamhábaltacht é a úsáid, fiú má cuireadh ar an eolas iad faoin bhféidearthacht go dtarlódh a leithéid. I gcás nach gceadaíonn dlínse an teorannú seo go hiomlán nó go páirteach, tá an dliteanas teoranta don mhéid is lú a cheadaíonn an dlí sin.

🤝  SLÁNAÍOCHT
Aontaíonn an t-úsáideoir na forbróirí agus na rannpháirtithe a shlánú agus a shaoradh ó aon éileamh, damáiste, caillteanas nó costas (lena n-áirítear costais dlí) a eascraíonn as a úsáid ar an bhfeidhmchlár nó as sárú na dtéarmaí seo.

🔒  PRÍOBHÁIDEACHT AGUS SEIRBHÍSÍ LÍONRA
Ní fheidhmíonn Voyager freastalaithe dá chuid féin, ní bhailíonn sé staitisticí úsáide agus níl teiliméadracht ar bith ann, ach ní feidhmchlár as líne é. Nuair a úsáidtear na feidhmeanna ábhartha, seoltar comhordanáidí nó ceantair gharbha agus an seoladh IP go díreach chuig tríú páirtithe: soláthraithe ródaithe (foinse, ceann scríbe agus pointí idir eatarthu), OpenStreetMap/Nominatim/Overpass (cuardach, geochódú aisiompaithe, pointí spéise, criosanna srianta, teorainneacha agus ceamaraí), Open-Meteo (comhordanáidí slánaithe), freastalaithe tíleanna léarscáile agus athsheachadáin Nostr (geohash ar leibhéal na cathrach). Foilsíonn tuairisc tráchta a suíomh beacht, an t-am, an t-inneachar agus an eochair phoiblí ar Nostr agus tá sí bréagainmnithe, ní gan ainm. Ní théann iarratais cheoil ach chuig an bhfreastalaí a chumraigh an t-úsáideoir féin; stóráiltear a dhintiúir ar an ngléas faoi chriptiú. Ritheann sintéis chainte agus aithint chainte go hiomlán ar an ngléas agus ní sheolann siad aon rud. Taispeántar glaonna agus teachtaireachtaí isteach agus, más rogha é, léitear os ard iad, agus caitear ansin uathu iad: ní stóráiltear riamh iad agus ní tharchuirtear riamh iad.

🎧  INNEACHAR AGUS CEADÚNÚ
Ní sheinneann Voyager ach ábhar a bhfuil ceart ag an úsáideoir cheana féin é a sheinm, ó fhreastalaithe a fheidhmíonn sé féin. Ní sholáthraíonn an feidhmchlár aon inneachar dá chuid féin ná aon bhealach chun é a fháil. Is ar an úsáideoir amháin atá an fhreagracht as dlíthiúlacht an ábhair a rochtaítear.

⚖️  INSCARTHACHT
Má chinntear nach bhfuil aon fhoráil de na téarmaí seo infhorfheidhmithe i ndlínse ar leith, teorannófar nó scoirfear an fhoráil sin a mhéid is lú is gá, agus fanfaidh na forálacha eile go léir i lánfheidhm.

Ach Voyager a úsáid, áit ar bith ar domhan, dearbhaíonn an t-úsáideoir gur léigh sé, gur thuig sé agus gur ghlac sé gan choinníoll le gach téarma thuas, agus glacann sé freagracht iomlán — agus gach riosca — as úsáid an fheidhmchláir agus as aon iarmhairt a eascraíonn as.''';
