// Voyager's safety and liability notice, German.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerDe = '''
Voyager ist ein experimentelles, quelloffenes und von der Gemeinschaft gepflegtes Fahrzeug-Dashboard. Es verbindet eine auf OpenStreetMap-Daten und dem Nostr-Protokoll basierende Navigation mit Medienwiedergabe, Wetterinformationen, Sprachsynthese und optionalen Telefoniefunktionen. Mit dem Herunterladen, Installieren oder Verwenden dieser App akzeptiert die Nutzerin oder der Nutzer alle nachstehenden Bedingungen vorbehaltlos und ohne räumliche Beschränkung:

🚗  SICHERHEIT IM STRASSENVERKEHR GEHT VOR
Die fahrende Person muss den Blick stets auf die Straße richten und alle geltenden Verkehrsregeln sowie die vorhandene Beschilderung befolgen; diese haben immer Vorrang vor jeder Anweisung der App. Bedienen Sie das Gerät niemals während der Fahrt; befestigen Sie es vor Fahrtantritt in einer zugelassenen, gut sichtbaren Halterung und wenden Sie die Aufmerksamkeit bei fahrendem Fahrzeug niemals von der Straße ab, um damit zu interagieren. In vielen Rechtsordnungen stellt bereits das Halten eines Geräts am Steuer eine Ordnungswidrigkeit dar, unabhängig davon, was das Gerät anzeigt.

🎵  MEDIEN UND TELEFONIE WÄHREND DER FAHRT
Musikwiedergabe, das Vorlesen von Nachrichten und die Anrufverwaltung sind Komfortfunktionen und werden zu denselben Bedingungen bereitgestellt wie alles andere in dieser App. Musik auszuwählen, eine Mediathek zu durchsuchen, eine Nachricht auf dem Bildschirm zu lesen oder ein Gespräch zu führen sind kognitive Belastungen, die die Fahrleistung mindern. Richten Sie die Wiedergabe vor Fahrtantritt ein und verwenden Sie bei fahrendem Fahrzeug die physischen Bedienelemente am Lenkrad statt des Touchscreens. Wo örtliches Recht die Telefonnutzung am Steuer einschränkt oder verbietet, geht dieses Recht vor und die entsprechenden Funktionen dürfen nicht verwendet werden.

⚠️  RISIKOÜBERNAHME — WELTWEIT
Mit der Nutzung von Voyager übernimmt die Nutzerin oder der Nutzer in jedem Land und unter jeder Rechtsordnung wissentlich und freiwillig ALLE mit der Nutzung verbundenen Risiken, einschließlich, aber nicht beschränkt auf: Verkehrsunfälle, Personenschäden, Tod, Sachschäden, Fahrzeugschäden, Bußgelder, Verwaltungsstrafen, Abschleppen, Beschlagnahme, strafrechtliche Haftung oder jede andere Folge, die sich mittelbar oder unmittelbar aus dem Vertrauen auf die App ergibt. Die Nutzerin oder der Nutzer trägt allein die volle Verantwortung für jede Fahr- und Navigationsentscheidung.

🚫  KEINE GEWÄHRLEISTUNG
Voyager wird ausdrücklich "WIE BESEHEN" und "WIE VERFÜGBAR" bereitgestellt, ohne jegliche ausdrückliche, stillschweigende oder gesetzliche Gewährleistung — einschließlich, ohne Einschränkung, der Gewährleistung von Richtigkeit, Vollständigkeit, Zuverlässigkeit, Verfügbarkeit, Marktgängigkeit, Eignung für einen bestimmten Zweck und Nichtverletzung von Rechten Dritter. Kartendaten, Routen, Geschwindigkeitsbegrenzungen, Blitzer und Angaben zu Umweltzonen und verkehrsbeschränkten Bereichen stammen aus offenen, von der Gemeinschaft gepflegten Quellen (OpenStreetMap, Overpass API), die für jedes Land, jede Region und jede Gemeinde jederzeit und ohne Vorankündigung unvollständig, veraltet oder unrichtig sein können. Die Nutzerin oder der Nutzer ist allein dafür verantwortlich, vor und während der Fahrt eigenständig zu prüfen, ob eine vorgeschlagene Route nach der offiziellen örtlichen Beschilderung und den geltenden Vorschriften zulässig und befahrbar ist.

📍  GENAUIGKEIT UND GPS
Die GPS-Positionsbestimmung kann ungenau oder nicht verfügbar sein. Alle Richtungsangaben, Entfernungen und Hinweise dienen ausschließlich der Orientierung und dürfen niemals als alleinige Grundlage einer Fahrentscheidung herangezogen werden.

🛡️  HAFTUNGSBESCHRÄNKUNG
Soweit nach dem anwendbaren Recht einer Rechtsordnung zulässig, haften die Entwickler, die Beitragenden und alle an der Erstellung oder Verbreitung von Voyager Beteiligten nicht für unmittelbare, mittelbare, beiläufige, Folge-, besondere, exemplarische oder Strafschäden jeder Art — einschließlich Personenschäden, Tod oder finanzieller Verluste —, die sich aus der Nutzung oder der Unmöglichkeit der Nutzung der App ergeben, selbst wenn auf die Möglichkeit solcher Schäden hingewiesen wurde. Soweit eine Rechtsordnung diese Beschränkung ganz oder teilweise nicht zulässt, ist die Haftung auf das dort gesetzlich zulässige Mindestmaß beschränkt.

🤝  FREISTELLUNG
Die Nutzerin oder der Nutzer stellt die Entwickler und Beitragenden von allen Ansprüchen, Schäden, Verlusten oder Kosten (einschließlich Anwaltskosten) frei, die sich aus der Nutzung der App oder aus einem Verstoß gegen diese Bedingungen ergeben.

🔒  DATENSCHUTZ UND NETZWERKDIENSTE
Voyager betreibt keine eigenen Server, erhebt keine Nutzungsstatistiken und enthält keinerlei Telemetrie, ist aber keine Offline-App. Bei Nutzung der jeweiligen Funktionen werden Koordinaten oder grobe Gebietsangaben sowie die IP-Adresse unmittelbar an Dritte übermittelt: an Routing-Anbieter (Start, Ziel und Zwischenziele), an OpenStreetMap/Nominatim/Overpass (Suche, umgekehrte Geokodierung, Points of Interest, verkehrsbeschränkte Zonen, Tempolimits und Blitzer), an Open-Meteo (gerundete Koordinaten), an Kartenkachel-Server und an Nostr-Relays (Geohash auf Stadtebene). Eine Verkehrsmeldung veröffentlicht ihre genaue Position, Uhrzeit, ihren Inhalt und den öffentlichen Schlüssel im Nostr-Netz und ist pseudonym, nicht anonym. Musikanfragen gehen ausschließlich an den von der Nutzerin oder dem Nutzer konfigurierten Server; die Zugangsdaten dafür werden verschlüsselt auf dem Gerät gespeichert. Sprachsynthese und Spracherkennung laufen vollständig auf dem Gerät und senden nichts. Eingehende Anrufe und Nachrichten werden angezeigt und optional vorgelesen und danach verworfen: Sie werden niemals gespeichert und niemals übertragen.

🎧  INHALTE UND LIZENZEN
Voyager gibt ausschließlich Medien wieder, zu deren Wiedergabe die Nutzerin oder der Nutzer bereits berechtigt ist, und zwar von selbst betriebenen Servern. Die App stellt keine eigenen Inhalte bereit und bietet keine Möglichkeit, welche zu beziehen. Die Verantwortung für die Rechtmäßigkeit der abgerufenen Inhalte liegt vollständig bei der Nutzerin oder dem Nutzer.

⚖️  SALVATORISCHE KLAUSEL
Sollte eine Bestimmung dieser Bedingungen in einer Rechtsordnung unwirksam sein, so wird sie auf das notwendige Mindestmaß beschränkt oder gestrichen; alle übrigen Bestimmungen bleiben in vollem Umfang wirksam.

Mit der Nutzung von Voyager bestätigt die Nutzerin oder der Nutzer weltweit, jede der vorstehenden Bedingungen gelesen, verstanden und vorbehaltlos akzeptiert zu haben, und übernimmt die volle und uneingeschränkte Verantwortung — sowie jedes Risiko — für die Nutzung der Anwendung und für alle daraus entstehenden Folgen.''';
