// Voyager's safety and liability notice, Dutch.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerNl = '''
Voyager is een experimenteel, opensource en door de gemeenschap onderhouden dashboard voor in de auto. Het combineert navigatie op basis van OpenStreetMap-gegevens en het Nostr-protocol met mediaweergave, weersinformatie, spraaksynthese en optionele telefoniefuncties. Door deze app te downloaden, te installeren of te gebruiken aanvaardt de gebruiker onvoorwaardelijk alle onderstaande voorwaarden, zonder territoriale beperking:

🚗  VERKEERSVEILIGHEID GAAT VOOR
De bestuurder moet de ogen altijd op de weg houden en alle geldende verkeersregels en aanwezige bebording naleven; die hebben altijd voorrang op elke aanwijzing van de app. Bedien het apparaat nooit tijdens het rijden; bevestig het vóór vertrek in een goedgekeurde, zichtbare houder en wend de aandacht nooit van de weg af om ermee te interageren terwijl het voertuig rijdt. In veel rechtsgebieden is het vasthouden van een apparaat achter het stuur op zichzelf al een overtreding, ongeacht wat het apparaat toont.

🎵  MEDIA EN TELEFONIE TIJDENS HET RIJDEN
Muziekweergave, het voorlezen van berichten en het afhandelen van oproepen zijn gemaksfuncties en worden onder dezelfde voorwaarden geleverd als al het andere in deze app. Muziek kiezen, door een bibliotheek bladeren, een bericht op het scherm lezen of een gesprek voeren zijn stuk voor stuk cognitieve belastingen die de rijprestaties verminderen. Stel de weergave vóór vertrek in en gebruik de fysieke bediening op het stuur in plaats van het aanraakscherm zodra het voertuig rijdt. Waar lokale wetgeving telefoongebruik achter het stuur beperkt of verbiedt, gaat die wetgeving voor en mogen de betreffende functies niet worden gebruikt.

⚠️  AANVAARDING VAN RISICO — WERELDWIJD
Door Voyager te gebruiken aanvaardt de gebruiker, in elk land en onder elk rechtsstelsel, welbewust en vrijwillig ALLE risico's die met dat gebruik samenhangen, met inbegrip van maar niet beperkt tot: verkeersongevallen, persoonlijk letsel, overlijden, materiële schade, schade aan het voertuig, boetes, bestuurlijke sancties, wegslepen, inbeslagname, strafrechtelijke aansprakelijkheid of elk ander gevolg dat direct of indirect voortvloeit uit het vertrouwen op de app. De gebruiker draagt als enige de volledige verantwoordelijkheid voor elke rij- en navigatiebeslissing.

🚫  GEEN GARANTIE
Voyager wordt strikt geleverd "ZOALS HET IS" en "ZOALS BESCHIKBAAR", zonder enige garantie, uitdrukkelijk, impliciet of wettelijk — met inbegrip van, zonder beperking, garanties van juistheid, volledigheid, betrouwbaarheid, beschikbaarheid, verkoopbaarheid, geschiktheid voor een bepaald doel en niet-inbreuk. Kaartgegevens, routes, snelheidslimieten, flitspalen en informatie over milieuzones en beperkt toegankelijke gebieden komen uit open, door de gemeenschap onderhouden bronnen (OpenStreetMap, Overpass API) die voor elk land, elke regio en elke gemeente onvolledig, verouderd of onjuist kunnen zijn, op elk moment en zonder aankondiging. Het is uitsluitend de verantwoordelijkheid van de gebruiker om vóór en tijdens de rit zelfstandig te controleren of een voorgestelde route is toegestaan en toegankelijk is volgens de officiële lokale bebording en regelgeving.

📍  NAUWKEURIGHEID EN GPS
GPS-positiebepaling kan onnauwkeurig of niet beschikbaar zijn. Alle aanwijzingen, afstanden en waarschuwingen zijn uitsluitend ter oriëntatie bedoeld en mogen nooit de enige grondslag van een rijbeslissing vormen.

🛡️  BEPERKING VAN AANSPRAKELIJKHEID
Voor zover maximaal toegestaan door het toepasselijke recht in enig rechtsgebied zijn de ontwikkelaars, de bijdragers en elke partij die betrokken is bij het maken of verspreiden van Voyager niet aansprakelijk voor directe, indirecte, incidentele, gevolg-, bijzondere, exemplarische of punitieve schade van welke aard dan ook — met inbegrip van persoonlijk letsel, overlijden of financieel verlies — die voortvloeit uit het gebruik of de onmogelijkheid tot gebruik van de app, zelfs indien gewezen op de mogelijkheid van dergelijke schade. Waar een rechtsgebied deze beperking geheel of gedeeltelijk niet toestaat, is de aansprakelijkheid beperkt tot het kleinst mogelijke wettelijk toegestane bedrag.

🤝  VRIJWARING
De gebruiker vrijwaart de ontwikkelaars en bijdragers van elke vordering, schade, verlies of kosten (met inbegrip van juridische kosten) die voortvloeien uit zijn of haar gebruik van de app of uit schending van deze voorwaarden.

🔒  PRIVACY EN NETWERKDIENSTEN
Voyager draait geen eigen servers, verzamelt geen gebruiksstatistieken en bevat geen enkele vorm van telemetrie, maar het is geen offline app. Wanneer de betreffende functies worden gebruikt, worden coördinaten of globale gebieden en het IP-adres rechtstreeks naar derden gestuurd: routeaanbieders (vertrek, bestemming en tussenpunten), OpenStreetMap/Nominatim/Overpass (zoeken, omgekeerde geocodering, nuttige plaatsen, beperkte zones, limieten en flitspalen), Open-Meteo (afgeronde coördinaten), kaarttegelservers en Nostr-relays (geohash op stadsniveau). Een verkeersmelding publiceert op Nostr de exacte positie, het tijdstip, de inhoud en de publieke sleutel en is pseudoniem, niet anoniem. Muziekverzoeken gaan uitsluitend naar de server die de gebruiker heeft ingesteld; de inloggegevens daarvan worden versleuteld op het apparaat bewaard. Spraaksynthese en spraakherkenning draaien volledig op het apparaat en versturen niets. Binnenkomende oproepen en berichten worden getoond en eventueel voorgelezen en daarna weggegooid: ze worden nooit opgeslagen en nooit verzonden.

🎧  INHOUD EN LICENTIES
Voyager speelt uitsluitend media af die de gebruiker al mag afspelen, vanaf servers die hij of zij zelf beheert. De app levert geen eigen inhoud en biedt geen enkele manier om inhoud te verkrijgen. De verantwoordelijkheid voor de rechtmatigheid van de geraadpleegde inhoud ligt volledig bij de gebruiker.

⚖️  SPLITSBAARHEID
Indien een bepaling van deze voorwaarden in een bepaald rechtsgebied niet afdwingbaar blijkt, wordt die bepaling beperkt of geschrapt tot het strikt noodzakelijke minimum, en blijven alle overige bepalingen onverkort van kracht.

Door Voyager te gebruiken, waar ook ter wereld, bevestigt de gebruiker elk van bovenstaande voorwaarden te hebben gelezen, begrepen en onvoorwaardelijk aanvaard, en aanvaardt hij of zij de volledige verantwoordelijkheid — en elk risico — voor het gebruik van de applicatie en voor elk gevolg daarvan.''';
