// Voyager's safety and liability notice, Lithuanian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerLt = '''
Voyager yra eksperimentinis, atvirojo kodo ir bendruomenės prižiūrimas automobilio prietaisų skydelis. Jis sujungia navigaciją, pagrįstą OpenStreetMap duomenimis ir Nostr protokolu, su medijos atkūrimu, orų informacija, kalbos sinteze ir pasirenkamomis telefono funkcijomis. Atsisiųsdamas, įdiegdamas arba naudodamas šią programėlę, naudotojas besąlygiškai sutinka su visomis toliau išdėstytomis sąlygomis be teritorinio apribojimo:

🚗  PIRMIAUSIA – SAUGUMAS KELYJE
Vairuotojas visada privalo žiūrėti į kelią ir laikytis visų galiojančių eismo taisyklių bei įrengtų kelio ženklų, kurie visada turi pirmenybę prieš bet kokį programėlės nurodymą. Niekada nenaudokite įrenginio vairuodami; prieš išvykdami pritvirtinkite jį patvirtintame, matomame laikiklyje ir niekada nenukreipkite dėmesio nuo kelio, kad su juo dirbtumėte, kol transporto priemonė juda. Daugelyje teisinių sistemų įrenginio laikymas rankoje prie vairo savaime yra pažeidimas, nesvarbu, ką įrenginys rodo.

🎵  MEDIJA IR TELEFONO NAUDOJIMAS VAIRUOJANT
Muzikos atkūrimas, žinučių skaitymas balsu ir skambučių tvarkymas yra patogumo funkcijos ir teikiamos tomis pačiomis sąlygomis kaip ir visa kita programėlėje. Muzikos pasirinkimas, bibliotekos naršymas, žinutės skaitymas ekrane ar pokalbio vedimas yra kognityvinė apkrova, mažinanti vairavimo kokybę. Nustatykite atkūrimą prieš išvykdami ir, kol transporto priemonė juda, naudokite fizinius vairo valdiklius, o ne jutiklinį ekraną. Ten, kur vietos teisė riboja arba draudžia naudotis telefonu prie vairo, ta teisė turi viršenybę ir atitinkamų funkcijų naudoti negalima.

⚠️  RIZIKOS PRISIĖMIMAS — VISAME PASAULYJE
Naudodamas Voyager bet kurioje šalyje ir pagal bet kurią teisinę sistemą, naudotojas sąmoningai ir savanoriškai prisiima VISAS su naudojimu susijusias rizikas, įskaitant, bet neapsiribojant: eismo įvykius, kūno sužalojimus, mirtį, turtinę žalą, transporto priemonės sugadinimą, baudas, administracines sankcijas, nutempimą, transporto priemonės areštą, baudžiamąją atsakomybę ar bet kokias kitas pasekmes, tiesiogiai arba netiesiogiai kylančias dėl pasitikėjimo programėle. Naudotojas vienas prisiima visą atsakomybę už kiekvieną vairavimo ir navigacijos sprendimą.

🚫  JOKIŲ GARANTIJŲ
Voyager teikiama griežtai "TOKIA, KOKIA YRA" ir "PAGAL PRIEINAMUMĄ", be jokių aiškiai išreikštų, numanomų ar įstatymų nustatytų garantijų — įskaitant, be apribojimų, garantijas dėl tikslumo, išsamumo, patikimumo, prieinamumo, tinkamumo parduoti, tinkamumo konkrečiam tikslui ir teisių nepažeidimo. Kartografiniai duomenys, maršrutai, greičio apribojimai, greičio matuokliai ir informacija apie riboto eismo zonas gaunami iš atvirų, bendruomenės prižiūrimų šaltinių (OpenStreetMap, Overpass API), kurie bet kuriai šaliai, regionui ar savivaldybei bet kuriuo metu ir be įspėjimo gali būti neišsamūs, pasenę arba netikslūs. Tik naudotojas atsako už tai, kad prieš kelionę ir jos metu savarankiškai patikrintų kiekvieno siūlomo maršruto teisėtumą ir pravažiuojamumą pagal oficialius vietos kelio ženklus ir taisykles.

📍  TIKSLUMAS IR GPS
GPS padėties nustatymas gali būti netikslus arba nepasiekiamas. Visi nurodymai, atstumai ir įspėjimai teikiami tik orientaciniais tikslais ir niekada negali būti vienintelis vairavimo sprendimo pagrindas.

🛡️  ATSAKOMYBĖS RIBOJIMAS
Kiek leidžia taikytina teisė bet kurioje jurisdikcijoje, kūrėjai, prisidėjusieji ir bet kuri šalis, dalyvaujanti kuriant ar platinant Voyager, neatsako už jokią tiesioginę, netiesioginę, atsitiktinę, išvestinę, specialiąją, pavyzdinę ar baudžiamąją žalą — įskaitant kūno sužalojimus, mirtį ar finansinius nuostolius —, kylančią dėl programėlės naudojimo ar negalėjimo ja naudotis, net jei buvo įspėti apie tokios žalos galimybę. Kai jurisdikcija visiškai ar iš dalies neleidžia tokio ribojimo, atsakomybė ribojama iki mažiausios ten teisės aktų leidžiamos apimties.

🤝  ŽALOS ATLYGINIMAS
Naudotojas įsipareigoja atlyginti ir apsaugoti kūrėjus bei prisidėjusiuosius nuo bet kokio reikalavimo, žalos, nuostolio ar išlaidų (įskaitant teisines išlaidas), kylančių dėl jo naudojimosi programėle arba šių sąlygų pažeidimo.

🔒  PRIVATUMAS IR TINKLO PASLAUGOS
Voyager neturi savo serverių, nerenka naudojimo statistikos ir neturi jokios telemetrijos, tačiau tai nėra neprisijungus veikianti programėlė. Naudojantis atitinkamomis funkcijomis, koordinatės arba apytikslės teritorijos ir IP adresas tiesiogiai siunčiami trečiosioms šalims: maršrutų paslaugų teikėjams (išvykimo taškas, tikslas ir tarpiniai taškai), OpenStreetMap/Nominatim/Overpass (paieška, atvirkštinis geokodavimas, lankytinos vietos, ribojimo zonos, apribojimai ir kameros), Open-Meteo (suapvalintos koordinatės), žemėlapių plytelių serveriams ir Nostr retransliatoriams (miesto lygmens geohash). Eismo pranešimas Nostr tinkle paskelbia savo tikslią vietą, laiką, turinį ir viešąjį raktą, todėl yra pseudonimiškas, o ne anoniminis. Muzikos užklausos siunčiamos tik į naudotojo paties sukonfigūruotą serverį; jo prisijungimo duomenys įrenginyje saugomi užšifruoti. Kalbos sintezė ir atpažinimas veikia visiškai įrenginyje ir nieko nesiunčia. Įeinantys skambučiai ir žinutės parodomi ir, pasirinkus, perskaitomi balsu, o po to atmetami: jie niekada nėra išsaugomi ir niekada neperduodami.

🎧  TURINYS IR LICENCIJOS
Voyager atkuria tik tokį turinį, kurį naudotojas jau turi teisę atkurti, iš serverių, kuriuos jis pats valdo. Programėlė neteikia savo turinio ir jokio būdo jam gauti. Atsakomybė už naudojamo turinio teisėtumą visiškai tenka naudotojui.

⚖️  NUOSTATŲ ATSKIRIAMUMAS
Jei kuri nors šių sąlygų nuostata konkrečioje jurisdikcijoje pripažįstama neįgyvendinama, ji ribojama arba pašalinama minimalia būtina apimtimi, o visos likusios nuostatos lieka visiškai galioti.

Naudodamasis Voyager bet kurioje pasaulio vietoje, naudotojas patvirtina, kad perskaitė, suprato ir besąlygiškai priėmė kiekvieną iš pirmiau nurodytų sąlygų, ir prisiima visišką bei visapusišką atsakomybę — taip pat visą riziką — už programėlės naudojimą ir bet kokias iš to kylančias pasekmes.''';
