// Voyager's safety and liability notice, Italian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerIt = '''
Voyager è un cruscotto per l'auto sperimentale, open source e mantenuto dalla community. Unisce una navigazione basata sui dati OpenStreetMap e sul protocollo Nostr con riproduzione multimediale, informazioni meteo, sintesi vocale e funzioni telefoniche facoltative. Scaricando, installando o utilizzando questa app, l'utente accetta incondizionatamente tutti i termini seguenti, senza limitazione di territorio:

🚗  PRIMA DI TUTTO LA SICUREZZA STRADALE
Il conducente deve tenere sempre gli occhi sulla strada e rispettare tutte le norme di circolazione e la segnaletica presente, che prevalgono sempre su qualunque indicazione dell'app. Non utilizzare mai il dispositivo durante la guida; fissarlo in un supporto omologato e visibile prima di partire e non distogliere mai l'attenzione dalla strada per interagire con esso a veicolo in movimento. In molti ordinamenti maneggiare un dispositivo alla guida costituisce di per sé un'infrazione, indipendentemente da ciò che il dispositivo mostra.

🎵  MULTIMEDIA E TELEFONIA DURANTE LA GUIDA
La riproduzione musicale, la lettura dei messaggi e la gestione delle chiamate sono funzioni di comodità e sono fornite alle stesse condizioni di tutto il resto dell'app. Scegliere la musica, sfogliare una libreria, leggere un messaggio sullo schermo o sostenere una conversazione sono carichi cognitivi che riducono le prestazioni di guida. Configurare la riproduzione prima di partire e usare i comandi fisici al volante anziché il touchscreen ogni volta che il veicolo è in movimento. Dove la legge locale limita o vieta l'uso del telefono alla guida, tale legge prevale e le funzioni corrispondenti non devono essere utilizzate.

⚠️  ASSUNZIONE DEL RISCHIO — IN TUTTO IL MONDO
Utilizzando Voyager, in qualsiasi Paese e sotto qualsiasi ordinamento, l'utente assume consapevolmente e volontariamente TUTTI i rischi connessi al suo utilizzo, inclusi a titolo esemplificativo e non esaustivo: incidenti stradali, lesioni personali, morte, danni a cose, danni al veicolo, multe, sanzioni amministrative, rimozione forzata, sequestro del veicolo, responsabilità penale o qualunque altra conseguenza derivante direttamente o indirettamente dall'affidamento sull'app. L'utente è l'unico pienamente responsabile di ogni decisione di guida e di navigazione.

🚫  NESSUNA GARANZIA
Voyager è fornita rigorosamente "COSÌ COM'È" e "COME DISPONIBILE", senza garanzie di alcun tipo, espresse, implicite o di legge — incluse, senza limitazione, garanzie di accuratezza, completezza, affidabilità, disponibilità, commerciabilità, idoneità a uno scopo particolare e non violazione di diritti altrui. Dati cartografici, percorsi, limiti di velocità, autovelox e informazioni sulle zone a traffico limitato (ZTL) provengono da fonti aperte e mantenute dalla community (OpenStreetMap, Overpass API) che possono essere incomplete, non aggiornate o inesatte per qualunque Paese, regione o comune, in qualsiasi momento e senza preavviso. L'utente è l'unico responsabile della verifica autonoma, prima e durante il viaggio, della legalità e dell'accessibilità di qualunque percorso suggerito rispetto alla segnaletica e alle norme locali ufficiali.

📍  PRECISIONE E GPS
Il posizionamento GPS può essere impreciso o non disponibile. Tutte le indicazioni, le distanze e gli avvisi sono forniti a solo titolo orientativo e non devono mai costituire l'unica base di una decisione di guida.

🛡️  LIMITAZIONE DI RESPONSABILITÀ
Nella massima misura consentita dalla legge applicabile in qualunque giurisdizione, gli sviluppatori, i contributori e chiunque sia coinvolto nella creazione o distribuzione di Voyager non saranno responsabili per danni diretti, indiretti, incidentali, consequenziali, speciali, esemplari o punitivi di qualsiasi natura — incluse lesioni personali, morte o perdite economiche — derivanti dall'uso o dall'impossibilità di usare l'app, anche se avvisati della possibilità di tali danni. Ove una giurisdizione non consenta in tutto o in parte tale limitazione, la responsabilità è limitata alla minima misura consentita dalla legge in quella giurisdizione.

🤝  MANLEVA
L'utente si impegna a manlevare e tenere indenni gli sviluppatori e i contributori da qualunque pretesa, danno, perdita o spesa (incluse le spese legali) derivante dall'uso dell'app da parte dell'utente o dalla violazione dei presenti termini.

🔒  PRIVACY E SERVIZI DI RETE
Voyager non ha server propri, non raccoglie statistiche e non contiene alcuna forma di telemetria, ma non è un'app offline. Quando si usano le relative funzioni, coordinate o aree approssimate e l'indirizzo IP vengono inviati direttamente a terze parti: provider di routing (origine, destinazione e tappe), OpenStreetMap/Nominatim/Overpass (ricerca, geocodifica inversa, punti di interesse, zone a traffico limitato, limiti e autovelox), Open-Meteo (coordinate arrotondate), server di tile cartografiche e relay Nostr (geohash a livello di città). Una segnalazione stradale pubblica su Nostr posizione esatta, orario, contenuto e chiave pubblica ed è pseudonima, non anonima. Le richieste musicali vanno al server configurato dall'utente e a nessun altro; le credenziali di quel server sono memorizzate cifrate sul dispositivo. Sintesi e riconoscimento vocale girano interamente sul dispositivo e non inviano nulla. Chiamate e messaggi in arrivo vengono mostrati ed eventualmente letti, poi scartati: non sono mai scritti su disco né trasmessi.

🎧  CONTENUTI E LICENZE
Voyager riproduce contenuti che l'utente ha già il diritto di riprodurre, da server gestiti dall'utente. Non fornisce contenuti propri né alcun mezzo per procurarseli. La responsabilità della liceità dei contenuti a cui si accede è interamente dell'utente.

⚖️  CLAUSOLA DI SALVAGUARDIA
Qualora una disposizione dei presenti termini risulti inapplicabile in una determinata giurisdizione, tale disposizione sarà limitata o esclusa nella misura minima necessaria e tutte le restanti disposizioni resteranno pienamente valide ed efficaci.

Utilizzando Voyager, ovunque nel mondo, l'utente conferma di aver letto, compreso e accettato incondizionatamente ogni termine sopra riportato e si assume la piena e completa responsabilità — e ogni rischio — per l'uso dell'applicazione e per qualunque conseguenza da esso derivante.''';
