// Voyager's safety and liability notice, Estonian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerEt = '''
Voyager on eksperimentaalne, avatud lähtekoodiga ja kogukonna hallatav autoarmatuurlaud. See ühendab OpenStreetMapi andmetel ja Nostri protokollil põhineva navigeerimise meediaesituse, ilmateabe, kõnesünteesi ja valikuliste telefonifunktsioonidega. Selle rakenduse allalaadimise, paigaldamise või kasutamisega nõustub kasutaja tingimusteta kõigi alljärgnevate tingimustega, ilma territoriaalse piiranguta:

🚗  ENNE KÕIKE LIIKLUSOHUTUS
Juht peab hoidma pilku alati teel ja järgima kõiki kehtivaid liiklusreegleid ja paigaldatud liiklusmärke, mis on alati ülimuslikud rakenduse mis tahes juhise suhtes. Ärge kunagi kasutage seadet sõidu ajal; kinnitage see enne teeleasumist heakskiidetud, nähtavasse hoidikusse ja ärge kunagi pöörake sõiduki liikumise ajal tähelepanu teelt kõrvale, et sellega tegeleda. Paljudes õiguskordades on seadme käes hoidmine rooli taga juba iseenesest rikkumine, sõltumata sellest, mida seade kuvab.

🎵  MEEDIA JA TELEFONIKASUTUS SÕIDU AJAL
Muusika esitamine, sõnumite ettelugemine ja kõnede käsitlemine on mugavusfunktsioonid ning neid pakutakse samadel tingimustel kui kõike muud rakenduses. Muusika valimine, kogu sirvimine, sõnumi lugemine ekraanilt või vestluse pidamine on kõik kognitiivsed koormused, mis halvendavad sõiduvõimet. Seadistage esitus enne teeleasumist ja kasutage sõiduki liikumise ajal puuteekraani asemel rooli füüsilisi juhtnuppe. Kui kohalik õigus piirab või keelab telefoni kasutamise rooli taga, on see õigus ülimuslik ja vastavaid funktsioone ei tohi kasutada.

⚠️  RISKI VÕTMINE — ÜLE MAAILMA
Voyageri kasutamisega võtab kasutaja mis tahes riigis ja mis tahes õiguskorra alusel teadlikult ja vabatahtlikult KÕIK selle kasutamisega seotud riskid, sealhulgas, kuid mitte ainult: liiklusõnnetused, kehavigastused, surm, varaline kahju, sõidukikahju, trahvid, haldussanktsioonid, teisaldamine, sõiduki arestimine, kriminaalvastutus või mis tahes muu tagajärg, mis tuleneb otseselt või kaudselt rakendusele tuginemisest. Kasutaja kannab üksi täielikku vastutust iga sõidu- ja navigeerimisotsuse eest.

🚫  GARANTII PUUDUMINE
Voyager antakse rangelt "NAGU ON" ja "NAGU SAADAVAL", ilma igasuguse sõnaselge, kaudse või seadusest tuleneva garantiita — sealhulgas piiranguteta garantiideta täpsuse, täielikkuse, usaldusväärsuse, kättesaadavuse, kaubandusliku kõlblikkuse, teatud otstarbeks sobivuse ja õiguste mitterikkumise osas. Kaardiandmed, marsruudid, kiirusepiirangud, kiiruskaamerad ning teave piiratud liiklusega alade kohta pärinevad avatud, kogukonna hallatavatest allikatest (OpenStreetMap, Overpass API), mis võivad mis tahes riigi, piirkonna või omavalitsuse puhul olla puudulikud, aegunud või ebatäpsed, igal ajal ja ette teatamata. Ainuüksi kasutaja vastutab selle eest, et ta enne reisi ja selle ajal iseseisvalt kontrolliks iga soovitatud marsruudi seaduslikkust ja läbitavust ametlike kohalike liiklusmärkide ja eeskirjade suhtes.

📍  TÄPSUS JA GPS
GPS-positsioneerimine võib olla ebatäpne või kättesaamatu. Kõik juhised, vahemaad ja hoiatused on üksnes soovituslikud ega tohi kunagi olla sõiduotsuse ainus alus.

🛡️  VASTUTUSE PIIRAMINE
Kohalduva õigusega igas jurisdiktsioonis lubatud maksimaalses ulatuses ei vastuta arendajad, kaastöötajad ega ükski Voyageri loomises või levitamises osalev pool mis tahes otsese, kaudse, juhusliku, tulenevalt tekkinud, erilise, hoiatava või karistusliku kahju eest — sealhulgas kehavigastused, surm või rahaline kahju —, mis tuleneb rakenduse kasutamisest või kasutamise võimatusest, isegi kui neid on sellise kahju võimalikkusest teavitatud. Kui jurisdiktsioon ei luba seda piirangut tervikuna või osaliselt, on vastutus piiratud väikseima ulatusega, mida sealne õigus lubab.

🤝  HÜVITAMINE
Kasutaja kohustub hüvitama ja vabastama arendajad ja kaastöötajad vastutusest mis tahes nõude, kahju, kaotuse või kulu eest (sealhulgas õigusabikulud), mis tuleneb tema rakenduse kasutamisest või käesolevate tingimuste rikkumisest.

🔒  PRIVAATSUS JA VÕRGUTEENUSED
Voyager ei pea ühtegi oma serverit, ei kogu kasutusstatistikat ega sisalda mingisugust telemeetriat, kuid see ei ole võrguühenduseta rakendus. Vastavate funktsioonide kasutamisel saadetakse koordinaadid või ligikaudsed alad ja IP-aadress otse kolmandatele osapooltele: marsruudipakkujatele (lähtepunkt, sihtkoht ja vahepunktid), OpenStreetMapile/Nominatimile/Overpassile (otsing, pöördgeokodeerimine, huvipunktid, piirangualad, piirangud ja kaamerad), Open-Meteole (ümardatud koordinaadid), kaardipaanide serveritele ja Nostri releedele (linna tasandi geohash). Liiklusteade avaldab Nostris oma täpse asukoha, aja, sisu ja avaliku võtme ning on pseudonüümne, mitte anonüümne. Muusikapäringud lähevad üksnes kasutaja enda seadistatud serverisse; selle mandaadid hoitakse seadmes krüpteeritult. Kõnesüntees ja kõnetuvastus töötavad täielikult seadmes ega saada midagi välja. Saabuvad kõned ja sõnumid kuvatakse ja loetakse soovi korral ette ning seejärel kõrvaldatakse: neid ei salvestata kunagi ega edastata kunagi.

🎧  SISU JA LITSENTSID
Voyager esitab üksnes sisu, mille esitamiseks on kasutajal juba õigus, serveritest, mida ta ise haldab. Rakendus ei paku oma sisu ega mingit viisi selle hankimiseks. Vastutus kasutatava sisu seaduslikkuse eest lasub täielikult kasutajal.

⚖️  SÄTETE LAHUTATAVUS
Kui mõni käesolevate tingimuste säte osutub konkreetses jurisdiktsioonis jõustamatuks, piiratakse seda või jäetakse see välja minimaalselt vajalikus ulatuses ning kõik ülejäänud sätted jäävad täies mahus kehtima.

Kasutades Voyagerit kus tahes maailmas, kinnitab kasutaja, et on lugenud, mõistnud ja tingimusteta aktsepteerinud iga ülaltoodud tingimust, ning võtab täieliku ja kogu vastutuse — samuti kogu riski — rakenduse kasutamise ja sellest tuleneva mis tahes tagajärje eest.''';
