// Voyager's safety and liability notice, Danish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerDa = '''
Voyager er et eksperimentelt, open source og fællesskabsvedligeholdt instrumentpanel til bilen. Det kombinerer navigation baseret på OpenStreetMap-data og Nostr-protokollen med medieafspilning, vejrinformation, talesyntese og valgfrie telefonifunktioner. Ved at downloade, installere eller bruge denne app accepterer brugeren ubetinget alle nedenstående vilkår, uden territorial begrænsning:

🚗  TRAFIKSIKKERHED FØRST
Føreren skal altid holde øjnene på vejen og overholde alle gældende færdselsregler og opsat skiltning, som altid har forrang for enhver anvisning fra appen. Betjen aldrig enheden under kørsel; fastgør den før afgang i en godkendt, synlig holder, og vend aldrig opmærksomheden væk fra vejen for at bruge den, mens køretøjet er i bevægelse. I mange retsordener er det i sig selv en overtrædelse at håndtere en enhed bag rattet, uanset hvad enheden viser.

🎵  MEDIER OG TELEFONI UNDER KØRSEL
Musikafspilning, oplæsning af beskeder og håndtering af opkald er bekvemmelighedsfunktioner og leveres på samme vilkår som alt andet i appen. At vælge musik, gennemse et bibliotek, læse en besked på skærmen eller føre en samtale er alle kognitive belastninger, der forringer køreevnen. Indstil afspilningen før afgang, og brug rattets fysiske betjeningsknapper frem for berøringsskærmen, når køretøjet er i bevægelse. Hvor lokal lovgivning begrænser eller forbyder brug af telefon bag rattet, har denne lovgivning forrang, og de tilsvarende funktioner må ikke bruges.

⚠️  RISIKOOVERTAGELSE — I HELE VERDEN
Ved at bruge Voyager påtager brugeren sig, i ethvert land og under enhver retsorden, bevidst og frivilligt ALLE risici forbundet med brugen, herunder men ikke begrænset til: trafikulykker, personskade, dødsfald, tingsskade, skade på køretøjet, bøder, administrative sanktioner, bortslæbning, beslaglæggelse, strafferetligt ansvar eller enhver anden følge, der direkte eller indirekte opstår af at forlade sig på appen. Brugeren bærer alene det fulde ansvar for enhver køre- og navigationsbeslutning.

🚫  INGEN GARANTI
Voyager leveres udelukkende "SOM DET ER" og "SOM TILGÆNGELIGT", uden nogen form for garanti, udtrykkelig, stiltiende eller lovbestemt — herunder, uden begrænsning, garantier for nøjagtighed, fuldstændighed, pålidelighed, tilgængelighed, salgbarhed, egnethed til et bestemt formål og ikke-krænkelse. Kortdata, ruter, hastighedsgrænser, fartkontroller og oplysninger om miljøzoner og trafikbegrænsede områder stammer fra åbne, fællesskabsvedligeholdte kilder (OpenStreetMap, Overpass API), som kan være ufuldstændige, forældede eller ukorrekte for ethvert land, enhver region og enhver kommune, til enhver tid og uden varsel. Det er alene brugerens ansvar selvstændigt at kontrollere, før og under turen, om en foreslået rute er lovlig og farbar i forhold til den officielle lokale skiltning og de lokale regler.

📍  NØJAGTIGHED OG GPS
GPS-positionering kan være unøjagtig eller utilgængelig. Alle anvisninger, afstande og advarsler er kun vejledende og må aldrig udgøre det eneste grundlag for en beslutning under kørsel.

🛡️  ANSVARSBEGRÆNSNING
I det omfang gældende lovgivning i enhver jurisdiktion tillader det, er udviklerne, bidragyderne og enhver part, der medvirker til at skabe eller distribuere Voyager, ikke ansvarlige for direkte, indirekte, hændelige, følge-, særlige, eksemplariske eller pønale skader af nogen art — herunder personskade, dødsfald eller økonomisk tab — der opstår som følge af brugen af eller manglende mulighed for at bruge appen, selv hvis de er blevet gjort opmærksom på muligheden for sådanne skader. Hvor en jurisdiktion ikke tillader hele eller dele af denne begrænsning, er ansvaret begrænset til det mindst mulige omfang, som lovgivningen der tillader.

🤝  SKADESLØSHOLDELSE
Brugeren forpligter sig til at holde udviklerne og bidragyderne skadesløse for ethvert krav, enhver skade, ethvert tab eller enhver udgift (herunder advokatomkostninger), der opstår som følge af brugerens brug af appen eller overtrædelse af disse vilkår.

🔒  PRIVATLIV OG NETVÆRKSTJENESTER
Voyager driver ingen egne servere, indsamler ingen brugsstatistik og indeholder ingen form for telemetri, men det er ikke en offline-app. Når de pågældende funktioner bruges, sendes koordinater eller omtrentlige områder samt IP-adressen direkte til tredjeparter: ruteudbydere (start, destination og mellempunkter), OpenStreetMap/Nominatim/Overpass (søgning, omvendt geokodning, interessepunkter, begrænsede zoner, hastighedsgrænser og fartkontroller), Open-Meteo (afrundede koordinater), kortfliseservere og Nostr-relæer (geohash på byniveau). En trafikmelding offentliggør sin præcise position, tidspunkt, sit indhold og sin offentlige nøgle på Nostr og er pseudonym, ikke anonym. Musikforespørgsler går udelukkende til den server, brugeren selv har konfigureret; adgangsoplysningerne til den gemmes krypteret på enheden. Talesyntese og talegenkendelse kører udelukkende på enheden og sender intet. Indgående opkald og beskeder vises og læses eventuelt op og kasseres derefter: de gemmes aldrig og sendes aldrig videre.

🎧  INDHOLD OG LICENSER
Voyager afspiller kun medier, som brugeren allerede har ret til at afspille, fra servere som brugeren selv driver. Appen leverer intet eget indhold og ingen måde at skaffe det på. Ansvaret for lovligheden af det anvendte indhold påhviler udelukkende brugeren.

⚖️  DELVIS UGYLDIGHED
Hvis en bestemmelse i disse vilkår findes uden retskraft i en given jurisdiktion, begrænses eller udgår den i det mindst mulige omfang, og alle øvrige bestemmelser forbliver fuldt gyldige.

Ved at bruge Voyager hvor som helst i verden bekræfter brugeren at have læst, forstået og ubetinget accepteret hvert af ovenstående vilkår og påtager sig det fulde og hele ansvar — og hele risikoen — for brugen af applikationen og enhver følge heraf.''';
