// Voyager's safety and liability notice, English.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerEn = '''
Voyager is an experimental, open-source, community-maintained in-car dashboard. It combines navigation based on OpenStreetMap data and the Nostr protocol with media playback, weather information, speech synthesis and optional telephony features. By downloading, installing or using this app, the user unconditionally accepts all of the following terms, without limitation of territory:

🚗  ROAD SAFETY FIRST
The driver must always keep their eyes on the road and comply with all applicable traffic laws and posted signage, which always take precedence over any instruction from the app. Never operate the device while driving; secure it in an approved, visible mount before setting off, and never divert attention from the road to interact with it while the vehicle is moving. In many jurisdictions handling a device while driving is itself an offence, regardless of what the device is showing.

🎵  MEDIA AND TELEPHONY WHILE DRIVING
Music playback, message reading and call handling are convenience features and are provided on the same terms as everything else in this app. Selecting music, browsing a library, reading a message on screen or conducting a conversation are all cognitive loads that reduce driving performance. Configure playback before setting off, and use the physical controls on the steering wheel rather than the touchscreen whenever the vehicle is in motion. Where local law restricts or prohibits telephone use while driving, that law takes precedence and the corresponding features must not be used.

⚠️  ASSUMPTION OF RISK — WORLDWIDE
By using Voyager, in any country and under any legal system, the user knowingly and voluntarily assumes ALL risks connected with its use, including but not limited to: traffic accidents, personal injury, death, property damage, vehicle damage, fines, administrative penalties, towing, impoundment, criminal liability, or any other consequence arising directly or indirectly from reliance on the app. The user alone bears full responsibility for every driving and navigation decision.

🚫  NO WARRANTY
Voyager is provided strictly "AS IS" and "AS AVAILABLE", without any warranty of any kind, whether express, implied, or statutory — including, without limitation, warranties of accuracy, completeness, reliability, availability, merchantability, fitness for a particular purpose, and non-infringement. Map data, routing, speed limits, speed cameras and restricted-traffic-zone (ZTL/ZAC/LTZ) information come from open, community-maintained sources (OpenStreetMap, Overpass API) that may be incomplete, outdated or inaccurate for any country, region or municipality, at any time and without notice. The user is solely responsible for independently verifying, before and during travel, the legality and accessibility of any suggested route against official local signage and regulations.

📍  ACCURACY & GPS
GPS positioning may be inaccurate or unavailable. All directions, distances and alerts are provided for guidance only and must never be relied upon as the sole basis for a driving decision.

🛡️  LIMITATION OF LIABILITY
To the maximum extent permitted by applicable law in any jurisdiction, the developers, contributors, and any party involved in creating or distributing Voyager shall not be liable for any direct, indirect, incidental, consequential, special, exemplary or punitive damages of any kind — including personal injury, death or financial loss — arising out of or related to the use or inability to use the app, even if advised of the possibility of such damages. Where a jurisdiction does not allow some or all of this limitation, liability is limited to the smallest extent permitted by law in that jurisdiction.

🤝  INDEMNIFICATION
The user agrees to indemnify and hold harmless the developers and contributors from any claim, damage, loss or expense (including legal fees) arising from the user's use of the app or violation of these terms.

🔒  PRIVACY AND NETWORK SERVICES
Voyager runs no first-party servers, collects no analytics and contains no telemetry of any kind, but it is not an offline app. When the relevant features are used, coordinates or coarse areas and the IP address are sent directly to third parties: routing providers (origin, destination and waypoints), OpenStreetMap/Nominatim/Overpass (search, reverse geocoding, POIs, restricted zones, limits and cameras), Open-Meteo (rounded coordinates), map-tile servers and Nostr relays (city-level geohash). A road report publishes its exact position, time, content and public key to Nostr and is pseudonymous, not anonymous. Music requests go to the server the user configured and to nowhere else; credentials for that server are stored encrypted on the device. Speech synthesis and speech recognition run entirely on the device and send nothing. Incoming calls and messages are displayed and optionally spoken, then discarded: they are never written to storage and never transmitted.

🎧  CONTENT AND LICENSING
Voyager plays media the user already has the right to play, from servers the user operates. It provides no content of its own and no means of obtaining any. Responsibility for the lawfulness of the media accessed rests entirely with the user.

⚖️  SEVERABILITY
If any provision of these terms is found unenforceable in a given jurisdiction, that provision shall be limited or severed to the minimum extent necessary, and all remaining provisions shall remain in full force and effect.

By using Voyager, anywhere in the world, the user confirms they have read, understood and unconditionally accepted every term above, and assumes full and complete responsibility — and all risk — for the use of the application and any consequence arising from it.''';
