// Voyager's safety and liability notice, Slovenian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerSl = '''
Voyager je eksperimentalna, odprtokodna in s strani skupnosti vzdrževana armaturna plošča za avtomobil. Združuje navigacijo, ki temelji na podatkih OpenStreetMap in protokolu Nostr, s predvajanjem medijev, vremenskimi informacijami, sintezo govora in izbirnimi telefonskimi funkcijami. S prenosom, namestitvijo ali uporabo te aplikacije uporabnik brezpogojno sprejema vse spodnje pogoje, brez ozemeljske omejitve:

🚗  NAJPREJ PROMETNA VARNOST
Voznik mora vedno gledati na cesto in upoštevati vsa veljavna prometna pravila in postavljeno signalizacijo, ki imajo vedno prednost pred katerimkoli navodilom aplikacije. Naprave nikoli ne upravljajte med vožnjo; pred odhodom jo pritrdite v odobreno, vidno držalo in med vožnjo vozila nikoli ne odvračajte pozornosti s ceste, da bi jo uporabljali. V mnogih pravnih redih je držanje naprave za volanom že samo po sebi prekršek, ne glede na to, kaj naprava prikazuje.

🎵  MULTIMEDIJA IN TELEFONIRANJE MED VOŽNJO
Predvajanje glasbe, branje sporočil na glas in upravljanje klicev so funkcije udobja in so na voljo pod enakimi pogoji kot vse drugo v aplikaciji. Izbiranje glasbe, brskanje po knjižnici, branje sporočila na zaslonu ali pogovor so kognitivne obremenitve, ki zmanjšujejo kakovost vožnje. Predvajanje nastavite pred odhodom in med vožnjo uporabljajte fizične tipke na volanu namesto zaslona na dotik. Kjer lokalna zakonodaja omejuje ali prepoveduje uporabo telefona med vožnjo, ima ta zakonodaja prednost in ustreznih funkcij ni dovoljeno uporabljati.

⚠️  PREVZEM TVEGANJA — PO VSEM SVETU
Z uporabo Voyagerja uporabnik v katerikoli državi in pod katerimkoli pravnim redom zavestno in prostovoljno prevzema VSA tveganja, povezana z njegovo uporabo, vključno z, a ne omejeno na: prometne nesreče, telesne poškodbe, smrt, premoženjsko škodo, škodo na vozilu, globe, upravne sankcije, odvoz vozila, zaseg vozila, kazensko odgovornost ali katerokoli drugo posledico, ki neposredno ali posredno izhaja iz zanašanja na aplikacijo. Uporabnik sam nosi polno odgovornost za vsako odločitev pri vožnji in navigaciji.

🚫  BREZ JAMSTVA
Voyager je na voljo izključno "TAK, KOT JE" in "GLEDE NA RAZPOLOŽLJIVOST", brez kakršnegakoli izrecnega, implicitnega ali zakonskega jamstva — vključno z, brez omejitev, jamstvi glede točnosti, popolnosti, zanesljivosti, razpoložljivosti, primernosti za prodajo, ustreznosti za določen namen in nekršenja pravic. Kartografski podatki, poti, omejitve hitrosti, hitrostne kamere ter podatki o območjih z omejenim prometom izvirajo iz odprtih, s strani skupnosti vzdrževanih virov (OpenStreetMap, Overpass API), ki so lahko za katerokoli državo, regijo ali občino nepopolni, zastareli ali netočni, kadarkoli in brez predhodnega obvestila. Izključno uporabnik je odgovoren, da pred potjo in med njo samostojno preveri zakonitost in prevoznost vsake predlagane poti glede na uradno lokalno signalizacijo in predpise.

📍  NATANČNOST IN GPS
Določanje položaja z GPS je lahko netočno ali nedostopno. Vsa navodila, razdalje in opozorila so zgolj informativne narave in nikoli ne smejo biti edina podlaga za odločitev med vožnjo.

🛡️  OMEJITEV ODGOVORNOSTI
V največjem obsegu, ki ga dopušča veljavno pravo v katerikoli jurisdikciji, razvijalci, sodelavci in katerakoli stran, vključena v ustvarjanje ali distribucijo Voyagerja, ne odgovarjajo za neposredno, posredno, naključno, posledično, posebno, eksemplarično ali kaznovalno škodo kakršnekoli vrste — vključno s telesnimi poškodbami, smrtjo ali finančno izgubo — ki izhaja iz uporabe ali nezmožnosti uporabe aplikacije, tudi če so bili opozorjeni na možnost take škode. Kjer jurisdikcija te omejitve v celoti ali delno ne dopušča, je odgovornost omejena na najmanjši obseg, ki ga tamkajšnje pravo dopušča.

🤝  ODŠKODNINA
Uporabnik se zavezuje, da bo razvijalce in sodelavce odškodoval in razbremenil odgovornosti za vsak zahtevek, škodo, izgubo ali strošek (vključno s pravnimi stroški), ki izhaja iz njegove uporabe aplikacije ali iz kršitve teh pogojev.

🔒  ZASEBNOST IN OMREŽNE STORITVE
Voyager ne upravlja lastnih strežnikov, ne zbira statistike uporabe in ne vsebuje nikakršne telemetrije, vendar ni aplikacija brez povezave. Pri uporabi ustreznih funkcij se koordinate ali grobo določena območja in naslov IP pošljejo neposredno tretjim osebam: ponudnikom izračuna poti (izhodišče, cilj in vmesne točke), OpenStreetMapu/Nominatimu/Overpassu (iskanje, obratno geokodiranje, točke zanimanja, območja omejitev, omejitve in kamere), Open-Meteu (zaokrožene koordinate), strežnikom kartografskih ploščic in relejem Nostr (geohash na ravni mesta). Prometna prijava na omrežju Nostr objavi svoj natančen položaj, čas, vsebino in javni ključ ter je psevdonimna, ne anonimna. Zahteve za glasbo gredo izključno na strežnik, ki ga je uporabnik sam nastavil; poverilnice zanj so na napravi shranjene šifrirano. Sinteza in prepoznavanje govora tečeta v celoti na napravi in ne pošiljata ničesar. Dohodni klici in sporočila se prikažejo in po želji preberejo na glas, nato pa se zavržejo: nikoli se ne shranijo in nikoli ne prenesejo.

🎧  VSEBINA IN LICENCE
Voyager predvaja le vsebino, ki jo uporabnik že sme predvajati, s strežnikov, ki jih sam upravlja. Aplikacija ne ponuja lastne vsebine niti kakršnegakoli načina za njeno pridobitev. Odgovornost za zakonitost dostopane vsebine je v celoti na uporabniku.

⚖️  LOČLJIVOST DOLOČIL
Če se katerokoli določilo teh pogojev v določeni jurisdikciji izkaže za neizvršljivo, bo omejeno ali izpuščeno v najmanjšem potrebnem obsegu, vsa preostala določila pa ostanejo v celoti veljavna.

Z uporabo Voyagerja kjerkoli na svetu uporabnik potrjuje, da je prebral, razumel in brezpogojno sprejel vsakega od zgornjih pogojev, ter prevzema polno in celotno odgovornost — pa tudi vse tveganje — za uporabo aplikacije in za katerokoli posledico, ki iz nje izhaja.''';
