// Voyager's safety and liability notice, Croatian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerHr = '''
Voyager je eksperimentalna, otvorenog koda i od zajednice održavana nadzorna ploča za automobil. Objedinjuje navigaciju temeljenu na podacima OpenStreetMapa i protokolu Nostr s reprodukcijom medija, vremenskim informacijama, sintezom govora i neobveznim telefonskim funkcijama. Preuzimanjem, instaliranjem ili korištenjem ove aplikacije korisnik bezuvjetno prihvaća sve niže navedene uvjete, bez teritorijalnog ograničenja:

🚗  PRVO SIGURNOST U PROMETU
Vozač mora uvijek gledati na cestu i poštovati sva važeća prometna pravila i postavljenu signalizaciju, koji uvijek imaju prednost pred bilo kojom uputom aplikacije. Nikada ne rukujte uređajem tijekom vožnje; prije polaska pričvrstite ga u odobreni, vidljivi držač i nikada ne skrećite pozornost s ceste kako biste s njim rukovali dok je vozilo u pokretu. U mnogim pravnim sustavima držanje uređaja za volanom samo po sebi predstavlja prekršaj, bez obzira na to što uređaj prikazuje.

🎵  MULTIMEDIJA I TELEFONIRANJE TIJEKOM VOŽNJE
Reprodukcija glazbe, čitanje poruka naglas i upravljanje pozivima funkcije su udobnosti i pružaju se pod istim uvjetima kao i sve ostalo u aplikaciji. Odabir glazbe, pregledavanje fonoteke, čitanje poruke na zaslonu ili vođenje razgovora kognitivna su opterećenja koja smanjuju kvalitetu vožnje. Postavite reprodukciju prije polaska i dok je vozilo u pokretu koristite fizičke upravljačke tipke na volanu umjesto zaslona osjetljivog na dodir. Ondje gdje lokalni propisi ograničavaju ili zabranjuju uporabu telefona za volanom, ti propisi imaju prednost i odgovarajuće se funkcije ne smiju koristiti.

⚠️  PREUZIMANJE RIZIKA — U CIJELOM SVIJETU
Korištenjem Voyagera korisnik u bilo kojoj zemlji i pod bilo kojim pravnim sustavom svjesno i dobrovoljno preuzima SVE rizike povezane s njegovom uporabom, uključujući, ali ne ograničavajući se na: prometne nesreće, tjelesne ozljede, smrt, materijalnu štetu, štetu na vozilu, novčane kazne, upravne sankcije, odvoz vozila, oduzimanje vozila, kaznenu odgovornost ili bilo koju drugu posljedicu koja izravno ili neizravno proizlazi iz oslanjanja na aplikaciju. Korisnik sam snosi punu odgovornost za svaku odluku pri vožnji i navigaciji.

🚫  BEZ JAMSTVA
Voyager se pruža isključivo "KAKAV JEST" i "PREMA DOSTUPNOSTI", bez ikakvih izričitih, podrazumijevanih ili zakonskih jamstava — uključujući, bez ograničenja, jamstva točnosti, potpunosti, pouzdanosti, dostupnosti, utrživosti, prikladnosti za određenu svrhu i nepovređivanja prava. Kartografski podaci, rute, ograničenja brzine, prometne kamere i podaci o zonama ograničenog prometa potječu iz otvorenih izvora koje održava zajednica (OpenStreetMap, Overpass API) i mogu biti nepotpuni, zastarjeli ili netočni za bilo koju zemlju, regiju ili općinu, u bilo kojem trenutku i bez najave. Isključivo je korisnik odgovoran samostalno provjeriti, prije i tijekom putovanja, zakonitost i prohodnost svake predložene rute u odnosu na službenu lokalnu signalizaciju i propise.

📍  TOČNOST I GPS
GPS pozicioniranje može biti netočno ili nedostupno. Sve upute, udaljenosti i upozorenja daju se isključivo u informativne svrhe i nikada ne smiju biti jedini temelj odluke pri vožnji.

🛡️  OGRANIČENJE ODGOVORNOSTI
U najvećoj mjeri dopuštenoj mjerodavnim pravom u bilo kojoj jurisdikciji, razvijatelji, suradnici i bilo koja strana uključena u stvaranje ili distribuciju Voyagera ne odgovaraju za izravnu, neizravnu, slučajnu, posljedičnu, posebnu, egzemplarnu ili kaznenu štetu bilo koje vrste — uključujući tjelesne ozljede, smrt ili financijski gubitak — koja proizlazi iz uporabe ili nemogućnosti uporabe aplikacije, čak i ako su bili upozoreni na mogućnost takve štete. Ondje gdje jurisdikcija ne dopušta ovo ograničenje u cijelosti ili djelomično, odgovornost je ograničena na najmanju mjeru koju tamošnje pravo dopušta.

🤝  NAKNADA ŠTETE
Korisnik se obvezuje obeštetiti i osloboditi odgovornosti razvijatelje i suradnike od svakog zahtjeva, štete, gubitka ili troška (uključujući pravne troškove) koji proizlazi iz njegove uporabe aplikacije ili iz kršenja ovih uvjeta.

🔒  PRIVATNOST I MREŽNE USLUGE
Voyager ne održava vlastite poslužitelje, ne prikuplja statistiku uporabe i ne sadrži nikakvu telemetriju, ali nije izvanmrežna aplikacija. Pri korištenju odgovarajućih funkcija koordinate ili grubo određena područja te IP adresa šalju se izravno trećim stranama: pružateljima usluga izračuna rute (polazište, odredište i međutočke), OpenStreetMapu/Nominatimu/Overpassu (pretraživanje, obrnuto geokodiranje, točke interesa, zone ograničenja, ograničenja i kamere), Open-Meteu (zaokružene koordinate), poslužiteljima kartografskih pločica i Nostr relejima (geohash na razini grada). Prometna prijava na Nostru objavljuje svoj točan položaj, vrijeme, sadržaj i javni ključ te je pseudonimna, a ne anonimna. Zahtjevi za glazbu odlaze isključivo na poslužitelj koji je korisnik sam konfigurirao; njegovi se pristupni podaci na uređaju pohranjuju šifrirano. Sinteza i prepoznavanje govora izvode se u cijelosti na uređaju i ništa ne šalju. Dolazni pozivi i poruke prikazuju se i po izboru čitaju naglas, a zatim se odbacuju: nikada se ne pohranjuju niti prenose.

🎧  SADRŽAJ I LICENCIJE
Voyager reproducira samo sadržaj koji korisnik već ima pravo reproducirati, s poslužitelja kojima sam upravlja. Aplikacija ne pruža vlastiti sadržaj niti bilo kakav način njegova pribavljanja. Odgovornost za zakonitost sadržaja kojemu se pristupa u cijelosti je na korisniku.

⚖️  ODVOJIVOST ODREDABA
Ako se neka odredba ovih uvjeta pokaže neprovedivom u određenoj jurisdikciji, bit će ograničena ili izostavljena u najmanjoj nužnoj mjeri, a sve ostale odredbe ostaju u cijelosti na snazi.

Korištenjem Voyagera bilo gdje u svijetu korisnik potvrđuje da je pročitao, razumio i bezuvjetno prihvatio svaki od gore navedenih uvjeta te preuzima punu i potpunu odgovornost — kao i sav rizik — za uporabu aplikacije i za bilo koju posljedicu koja iz nje proizlazi.''';
