// Voyager's safety and liability notice, Finnish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerFi = '''
Voyager on kokeellinen, avoimen lähdekoodin ja yhteisön ylläpitämä auton kojelauta. Se yhdistää OpenStreetMap-aineistoon ja Nostr-protokollaan perustuvan navigoinnin median toistoon, säätietoihin, puhesynteesiin ja valinnaisiin puhelintoimintoihin. Lataamalla, asentamalla tai käyttämällä tätä sovellusta käyttäjä hyväksyy ehdoitta kaikki seuraavat ehdot ilman alueellista rajoitusta:

🚗  LIIKENNETURVALLISUUS ENSIN
Kuljettajan on pidettävä katse aina tiessä ja noudatettava kaikkia voimassa olevia liikennesääntöjä ja liikennemerkkejä, jotka menevät aina sovelluksen ohjeiden edelle. Älä koskaan käytä laitetta ajon aikana; kiinnitä se ennen liikkeellelähtöä hyväksyttyyn, näkyvään telineeseen äläkä koskaan käännä huomiotasi pois tiestä käyttääksesi sitä ajoneuvon liikkuessa. Monissa oikeusjärjestelmissä laitteen käsittely ratin takana on jo sellaisenaan rikkomus riippumatta siitä, mitä laite näyttää.

🎵  MEDIA JA PUHELIMEN KÄYTTÖ AJON AIKANA
Musiikin toisto, viestien lukeminen ääneen ja puhelujen käsittely ovat mukavuustoimintoja, ja ne tarjotaan samoin ehdoin kuin kaikki muukin tässä sovelluksessa. Musiikin valitseminen, kirjaston selaaminen, viestin lukeminen näytöltä tai keskustelun käyminen ovat kaikki kognitiivista kuormaa, joka heikentää ajosuoritusta. Määritä toisto ennen liikkeellelähtöä ja käytä ohjauspyörän fyysisiä painikkeita kosketusnäytön sijaan aina ajoneuvon liikkuessa. Jos paikallinen laki rajoittaa tai kieltää puhelimen käytön ajaessa, laki menee edelle eikä vastaavia toimintoja saa käyttää.

⚠️  RISKIN OTTAMINEN — MAAILMANLAAJUISESTI
Käyttämällä Voyageria käyttäjä ottaa missä tahansa maassa ja minkä tahansa oikeusjärjestelmän alaisuudessa tietoisesti ja vapaaehtoisesti KAIKKI käyttöön liittyvät riskit, mukaan lukien mutta niihin rajoittumatta: liikenneonnettomuudet, henkilövahingot, kuolema, omaisuusvahingot, ajoneuvovahingot, sakot, hallinnolliset seuraamukset, hinaus, takavarikointi, rikosoikeudellinen vastuu tai mikä tahansa muu seuraus, joka aiheutuu suoraan tai välillisesti sovellukseen luottamisesta. Käyttäjä kantaa yksin täyden vastuun jokaisesta ajo- ja navigointipäätöksestä.

🚫  EI TAKUUTA
Voyager toimitetaan tiukasti "SELLAISENAAN" ja "SITEN KUIN SE ON SAATAVILLA" ilman minkäänlaista nimenomaista, hiljaista tai lakisääteistä takuuta — mukaan lukien rajoituksetta takuut tarkkuudesta, täydellisyydestä, luotettavuudesta, saatavuudesta, kaupallisesta hyödynnettävyydestä, soveltuvuudesta tiettyyn tarkoitukseen ja loukkaamattomuudesta. Kartta-aineistot, reitit, nopeusrajoitukset, nopeusvalvontakamerat sekä tiedot rajoitetun liikenteen alueista ovat peräisin avoimista, yhteisön ylläpitämistä lähteistä (OpenStreetMap, Overpass API), jotka voivat olla puutteellisia, vanhentuneita tai virheellisiä minkä tahansa maan, alueen tai kunnan osalta, milloin tahansa ja ilman ennakkoilmoitusta. Käyttäjä on yksin vastuussa siitä, että hän tarkistaa itsenäisesti ennen matkaa ja sen aikana ehdotetun reitin laillisuuden ja kulkukelpoisuuden virallisiin paikallisiin liikennemerkkeihin ja määräyksiin nähden.

📍  TARKKUUS JA GPS
GPS-paikannus voi olla epätarkkaa tai se ei ole käytettävissä. Kaikki ohjeet, etäisyydet ja varoitukset annetaan vain suuntaa antavina, eivätkä ne saa koskaan olla ajopäätöksen ainoa peruste.

🛡️  VASTUUNRAJOITUS
Sovellettavan lain sallimissa enimmäisrajoissa millä tahansa lainkäyttöalueella kehittäjät, avustajat ja kaikki Voyagerin luomiseen tai jakeluun osallistuvat osapuolet eivät vastaa mistään välittömistä, välillisistä, satunnaisista, seurannais-, erityisistä, esimerkillisistä tai rankaisevista vahingoista — mukaan lukien henkilövahingot, kuolema tai taloudelliset menetykset — jotka aiheutuvat sovelluksen käytöstä tai kyvyttömyydestä käyttää sitä, vaikka mahdollisuudesta tällaisiin vahinkoihin olisi ilmoitettu. Jos lainkäyttöalue ei salli tätä rajoitusta kokonaan tai osittain, vastuu rajoitetaan pienimpään siellä lain sallimaan määrään.

🤝  VAHINGONKORVAUSVELVOLLISUUS
Käyttäjä sitoutuu vapauttamaan kehittäjät ja avustajat vastuusta kaikkien vaatimusten, vahinkojen, menetysten tai kulujen (mukaan lukien oikeudenkäyntikulut) osalta, jotka aiheutuvat käyttäjän sovelluksen käytöstä tai näiden ehtojen rikkomisesta.

🔒  YKSITYISYYS JA VERKKOPALVELUT
Voyager ei ylläpidä omia palvelimia, ei kerää käyttötilastoja eikä sisällä minkäänlaista telemetriaa, mutta se ei ole offline-sovellus. Kun kyseisiä toimintoja käytetään, koordinaatit tai karkeat alueet sekä IP-osoite lähetetään suoraan kolmansille osapuolille: reititinpalveluille (lähtöpaikka, määränpää ja välipisteet), OpenStreetMapille/Nominatimille/Overpassille (haku, käänteinen geokoodaus, kohdepisteet, rajoitetut alueet, rajoitukset ja kamerat), Open-Meteolle (pyöristetyt koordinaatit), karttalaattapalvelimille ja Nostr-releille (kaupunkitason geohash). Liikenneilmoitus julkaisee Nostrissa tarkan sijaintinsa, ajankohdan, sisällön ja julkisen avaimen, ja se on peitenimellä tehty, ei anonyymi. Musiikkipyynnöt menevät vain käyttäjän itsensä määrittämälle palvelimelle; sen tunnistetiedot tallennetaan laitteelle salattuina. Puhesynteesi ja puheentunnistus toimivat kokonaan laitteessa eivätkä lähetä mitään. Saapuvat puhelut ja viestit näytetään ja luetaan valinnaisesti ääneen, minkä jälkeen ne hylätään: niitä ei koskaan tallenneta eikä lähetetä eteenpäin.

🎧  SISÄLTÖ JA LISENSSIT
Voyager toistaa vain sisältöä, jonka toistamiseen käyttäjällä on jo oikeus, käyttäjän itsensä ylläpitämiltä palvelimilta. Sovellus ei tarjoa omaa sisältöä eikä mitään keinoa hankkia sitä. Vastuu käytetyn sisällön laillisuudesta on kokonaan käyttäjällä.

⚖️  EHTOJEN ERILLISYYS
Jos jokin näiden ehtojen määräys todetaan täytäntöönpanokelvottomaksi tietyllä lainkäyttöalueella, sitä rajoitetaan tai se poistetaan vain välttämättömässä laajuudessa, ja kaikki muut määräykset pysyvät täysin voimassa.

Käyttämällä Voyageria missä tahansa maailmassa käyttäjä vahvistaa lukeneensa, ymmärtäneensä ja hyväksyneensä ehdoitta jokaisen edellä mainitun ehdon sekä ottavansa täyden ja kokonaisvaltaisen vastuun — ja koko riskin — sovelluksen käytöstä ja kaikista siitä aiheutuvista seurauksista.''';
