// Voyager's safety and liability notice, Polish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerPl = '''
Voyager to eksperymentalny, otwartoźródłowy i utrzymywany przez społeczność panel samochodowy. Łączy nawigację opartą na danych OpenStreetMap i protokole Nostr z odtwarzaniem multimediów, informacjami pogodowymi, syntezą mowy oraz opcjonalnymi funkcjami telefonicznymi. Pobierając, instalując lub używając tej aplikacji, użytkownik bezwarunkowo akceptuje wszystkie poniższe warunki, bez ograniczeń terytorialnych:

🚗  BEZPIECZEŃSTWO NA DRODZE PRZEDE WSZYSTKIM
Kierowca musi zawsze patrzeć na drogę i przestrzegać wszystkich obowiązujących przepisów ruchu drogowego oraz oznakowania, które zawsze mają pierwszeństwo przed jakąkolwiek wskazówką aplikacji. Nigdy nie obsługuj urządzenia podczas jazdy; przed wyruszeniem zamocuj je w atestowanym, widocznym uchwycie i nigdy nie odrywaj uwagi od drogi, aby z niego korzystać, gdy pojazd jest w ruchu. W wielu porządkach prawnych trzymanie urządzenia w ręku podczas jazdy samo w sobie stanowi wykroczenie, niezależnie od tego, co urządzenie wyświetla.

🎵  MULTIMEDIA I TELEFONIA PODCZAS JAZDY
Odtwarzanie muzyki, odczytywanie wiadomości i obsługa połączeń to funkcje wygody, udostępniane na tych samych warunkach co reszta aplikacji. Wybieranie muzyki, przeglądanie biblioteki, czytanie wiadomości na ekranie czy prowadzenie rozmowy to obciążenia poznawcze, które pogarszają jakość prowadzenia pojazdu. Skonfiguruj odtwarzanie przed wyruszeniem i korzystaj z fizycznych przycisków na kierownicy zamiast z ekranu dotykowego, gdy pojazd jest w ruchu. Tam, gdzie prawo miejscowe ogranicza lub zakazuje korzystania z telefonu podczas jazdy, prawo to ma pierwszeństwo, a odpowiednie funkcje nie mogą być używane.

⚠️  PRZYJĘCIE RYZYKA — NA CAŁYM ŚWIECIE
Korzystając z Voyagera, w dowolnym kraju i pod dowolnym systemem prawnym, użytkownik świadomie i dobrowolnie przyjmuje WSZELKIE ryzyko związane z jego użytkowaniem, w tym między innymi: wypadki drogowe, obrażenia ciała, śmierć, szkody majątkowe, uszkodzenie pojazdu, mandaty, kary administracyjne, odholowanie, zatrzymanie pojazdu, odpowiedzialność karną lub jakiekolwiek inne następstwa wynikające bezpośrednio lub pośrednio z polegania na aplikacji. Użytkownik ponosi wyłączną i pełną odpowiedzialność za każdą decyzję dotyczącą jazdy i nawigacji.

🚫  BRAK GWARANCJI
Voyager jest udostępniany wyłącznie w stanie "TAKIM, JAKI JEST" oraz "W MIARĘ DOSTĘPNOŚCI", bez jakichkolwiek gwarancji wyraźnych, dorozumianych lub ustawowych — w tym, bez ograniczeń, gwarancji dokładności, kompletności, niezawodności, dostępności, przydatności handlowej, przydatności do określonego celu oraz nienaruszania praw osób trzecich. Dane kartograficzne, trasy, ograniczenia prędkości, fotoradary oraz informacje o strefach ograniczonego ruchu pochodzą z otwartych, utrzymywanych przez społeczność źródeł (OpenStreetMap, Overpass API), które mogą być niekompletne, nieaktualne lub nieprawidłowe dla dowolnego kraju, regionu lub gminy, w dowolnym momencie i bez uprzedzenia. Wyłącznie użytkownik odpowiada za samodzielne sprawdzenie, przed podróżą i w jej trakcie, legalności i przejezdności każdej proponowanej trasy w zestawieniu z oficjalnym oznakowaniem i przepisami lokalnymi.

📍  DOKŁADNOŚĆ I GPS
Pozycjonowanie GPS może być niedokładne lub niedostępne. Wszystkie wskazówki, odległości i ostrzeżenia mają charakter wyłącznie orientacyjny i nigdy nie mogą stanowić jedynej podstawy decyzji podejmowanej podczas jazdy.

🛡️  OGRANICZENIE ODPOWIEDZIALNOŚCI
W najszerszym zakresie dozwolonym przez prawo właściwe w danej jurysdykcji twórcy, współautorzy oraz wszelkie podmioty uczestniczące w tworzeniu lub rozpowszechnianiu Voyagera nie ponoszą odpowiedzialności za jakiekolwiek szkody bezpośrednie, pośrednie, uboczne, następcze, szczególne, przykładowe lub karne — w tym obrażenia ciała, śmierć lub straty finansowe — wynikające z korzystania lub niemożności korzystania z aplikacji, nawet jeśli zostali poinformowani o możliwości ich wystąpienia. Jeżeli dana jurysdykcja nie dopuszcza tego ograniczenia w całości lub w części, odpowiedzialność jest ograniczona do najmniejszego zakresu dopuszczalnego przez tamtejsze prawo.

🤝  ZWOLNIENIE Z ODPOWIEDZIALNOŚCI
Użytkownik zobowiązuje się zwolnić twórców i współautorów z odpowiedzialności za wszelkie roszczenia, szkody, straty lub wydatki (w tym koszty obsługi prawnej) wynikające z korzystania przez niego z aplikacji lub z naruszenia niniejszych warunków.

🔒  PRYWATNOŚĆ I USŁUGI SIECIOWE
Voyager nie prowadzi własnych serwerów, nie zbiera statystyk użycia i nie zawiera żadnej telemetrii, ale nie jest aplikacją offline. Podczas korzystania z odpowiednich funkcji współrzędne lub przybliżone obszary oraz adres IP są wysyłane bezpośrednio do podmiotów trzecich: dostawców wyznaczania tras (punkt początkowy, cel i punkty pośrednie), OpenStreetMap/Nominatim/Overpass (wyszukiwanie, geokodowanie odwrotne, punkty użyteczności, strefy ograniczonego ruchu, ograniczenia i fotoradary), Open-Meteo (zaokrąglone współrzędne), serwerów kafelków mapy oraz przekaźników Nostr (geohash na poziomie miasta). Zgłoszenie drogowe publikuje w sieci Nostr dokładną pozycję, czas, treść i klucz publiczny i jest pseudonimowe, a nie anonimowe. Żądania muzyczne trafiają wyłącznie do serwera skonfigurowanego przez użytkownika; dane logowania do niego są przechowywane na urządzeniu w postaci zaszyfrowanej. Synteza i rozpoznawanie mowy działają w całości na urządzeniu i niczego nie wysyłają. Połączenia przychodzące i wiadomości są wyświetlane i opcjonalnie odczytywane na głos, a następnie odrzucane: nigdy nie są zapisywane ani przesyłane.

🎧  TREŚCI I LICENCJE
Voyager odtwarza wyłącznie treści, do których użytkownik już ma prawo, z serwerów, którymi sam zarządza. Aplikacja nie dostarcza własnych treści ani żadnego sposobu ich pozyskania. Odpowiedzialność za legalność odtwarzanych treści spoczywa w całości na użytkowniku.

⚖️  KLAUZULA SALWATORYJNA
Jeżeli którekolwiek postanowienie niniejszych warunków okaże się niewykonalne w danej jurysdykcji, zostanie ono ograniczone lub usunięte w minimalnym niezbędnym zakresie, a wszystkie pozostałe postanowienia zachowają pełną moc obowiązującą.

Korzystając z Voyagera w dowolnym miejscu na świecie, użytkownik potwierdza, że przeczytał, zrozumiał i bezwarunkowo zaakceptował każdy z powyższych warunków, oraz przyjmuje pełną i całkowitą odpowiedzialność — a także całe ryzyko — za korzystanie z aplikacji i wszelkie tego następstwa.''';
