// Voyager's safety and liability notice, Maltese.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerMt = '''
Voyager huwa dashboard sperimentali għall-karozza, b'sors miftuħ u miżmum mill-komunità. Jgħaqqad navigazzjoni bbażata fuq id-data ta' OpenStreetMap u l-protokoll Nostr ma' riproduzzjoni ta' midja, informazzjoni dwar it-temp, sinteżi tal-vuċi u funzjonijiet telefoniċi fakultattivi. Meta jniżżel, jinstalla jew juża din l-applikazzjoni, l-utent jaċċetta bla kundizzjoni t-termini kollha li ġejjin, mingħajr limitazzjoni territorjali:

🚗  L-EWWEL IS-SIGURTÀ FIT-TRIQ
Is-sewwieq għandu dejjem iżomm għajnejh fuq it-triq u jħares ir-regoli tat-traffiku kollha applikabbli u s-sinjalazzjoni mwaħħla, li dejjem jieħdu preċedenza fuq kwalunkwe istruzzjoni tal-applikazzjoni. Qatt tuża l-apparat waqt is-sewqan; qabel titlaq waħħlu f'sostenn approvat u viżibbli, u qatt iddawwarx l-attenzjoni tiegħek mit-triq biex tinteraġixxi miegħu waqt li l-vettura tkun miexja. F'ħafna ġurisdizzjonijiet, iż-żamma ta' apparat f'idejk wara l-isteering hija fiha nnifisha reat, ikun xi jkun li juri l-apparat.

🎵  MIDJA U TELEFONIJA WAQT IS-SEWQAN
Ir-riproduzzjoni tal-mużika, il-qari tal-messaġġi u l-immaniġġjar tat-telefonati huma funzjonijiet ta' konvenjenza u jingħataw bl-istess kundizzjonijiet bħal kull ħaġa oħra fl-applikazzjoni. L-għażla tal-mużika, it-tfittxija f'librerija, il-qari ta' messaġġ fuq l-iskrin jew iż-żamma ta' konverżazzjoni huma kollha piżijiet konjittivi li jnaqqsu l-prestazzjoni fis-sewqan. Issettja r-riproduzzjoni qabel titlaq u uża l-kontrolli fiżiċi fuq l-isteering minflok l-iskrin tal-mess kull meta l-vettura tkun miexja. Fejn il-liġi lokali tillimita jew tipprojbixxi l-użu tat-telefown waqt is-sewqan, dik il-liġi tieħu preċedenza u l-funzjonijiet korrispondenti m'għandhomx jintużaw.

⚠️  ASSUNZJONI TAR-RISKJU — MAD-DINJA KOLLHA
Bl-użu ta' Voyager, fi kwalunkwe pajjiż u taħt kwalunkwe sistema legali, l-utent jassumi konxjament u volontarjament IR-RISKJI KOLLHA marbuta mal-użu tiegħu, inklużi iżda mhux limitati għal: inċidenti tat-traffiku, korriment personali, mewt, ħsara lill-proprjetà, ħsara lill-vettura, multi, sanzjonijiet amministrattivi, irmunkar, konfiska tal-vettura, responsabbiltà kriminali, jew kwalunkwe konsegwenza oħra li tirriżulta direttament jew indirettament mid-dipendenza fuq l-applikazzjoni. L-utent waħdu jġorr ir-responsabbiltà sħiħa għal kull deċiżjoni ta' sewqan u ta' navigazzjoni.

🚫  L-EBDA GARANZIJA
Voyager jingħata strettament "KIF INHU" u "SKONT ID-DISPONIBBILTÀ", mingħajr ebda garanzija ta' kwalunkwe tip, espressa, impliċita jew statutorja — inklużi, mingħajr limitazzjoni, garanziji ta' eżattezza, kompletezza, affidabbiltà, disponibbiltà, kummerċjabbiltà, idoneità għal skop partikolari u nuqqas ta' ksur ta' drittijiet. Id-data kartografika, ir-rotot, il-limiti tal-veloċità, il-kameras tal-veloċità u l-informazzjoni dwar żoni b'traffiku ristrett ġejjin minn sorsi miftuħa miżmuma mill-komunità (OpenStreetMap, Overpass API) li jistgħu jkunu inkompleti, skaduti jew ineżatti għal kwalunkwe pajjiż, reġjun jew lokalità, fi kwalunkwe ħin u mingħajr avviż. Hija r-responsabbiltà unika tal-utent li jivverifika b'mod indipendenti, qabel u waqt il-vjaġġ, il-legalità u l-aċċessibbiltà ta' kwalunkwe rotta suġġerita meta mqabbla mas-sinjalazzjoni u r-regolamenti lokali uffiċjali.

📍  EŻATTEZZA U GPS
Il-pożizzjonament bil-GPS jista' jkun ineżatt jew mhux disponibbli. L-indikazzjonijiet, id-distanzi u t-twissijiet kollha jingħataw biss bħala gwida u qatt m'għandhom ikunu l-unika bażi ta' deċiżjoni waqt is-sewqan.

🛡️  LIMITAZZJONI TAR-RESPONSABBILTÀ
Sal-massimu permess mil-liġi applikabbli fi kwalunkwe ġurisdizzjoni, l-iżviluppaturi, il-kontributuri u kwalunkwe parti involuta fil-ħolqien jew fid-distribuzzjoni ta' Voyager mhumiex responsabbli għal ebda dannu dirett, indirett, inċidentali, konsegwenzjali, speċjali, eżemplari jew punittiv ta' kwalunkwe tip — inklużi korriment personali, mewt jew telf finanzjarju — li jirriżulta mill-użu jew mill-impossibbiltà tal-użu tal-applikazzjoni, anke jekk kienu avżati bil-possibbiltà ta' tali danni. Fejn ġurisdizzjoni ma tippermettix din il-limitazzjoni kollha jew parti minnha, ir-responsabbiltà hija limitata sal-inqas ammont permess mil-liġi hemmhekk.

🤝  INDENNIZZ
L-utent jaqbel li jindennizza u jżomm indenni lill-iżviluppaturi u lill-kontributuri minn kwalunkwe pretensjoni, dannu, telf jew spiża (inklużi spejjeż legali) li tirriżulta mill-użu tiegħu tal-applikazzjoni jew minn ksur ta' dawn it-termini.

🔒  PRIVATEZZA U SERVIZZI TA' NETWERK
Voyager ma jħaddem l-ebda server tiegħu, ma jiġbor l-ebda statistika ta' użu u ma fih l-ebda telemetrija, iżda mhuwiex applikazzjoni offline. Meta jintużaw il-funzjonijiet rilevanti, koordinati jew żoni approssimattivi u l-indirizz IP jintbagħtu direttament lil terzi: fornituri tar-rotot (punt tat-tluq, destinazzjoni u punti intermedji), OpenStreetMap/Nominatim/Overpass (tfittxija, geokodifikazzjoni inversa, punti ta' interess, żoni ristretti, limiti u kameras), Open-Meteo (koordinati arrotondati), servers tal-madum tal-mapep u relays ta' Nostr (geohash fil-livell tal-belt). Rapport tat-traffiku jippubblika fuq Nostr il-pożizzjoni eżatta tiegħu, il-ħin, il-kontenut u ċ-ċavetta pubblika, u huwa psewdonimu, mhux anonimu. It-talbiet għall-mużika jmorru biss għand is-server ikkonfigurat mill-utent; il-kredenzjali tiegħu jinħażnu kriptati fuq l-apparat. Is-sinteżi u r-rikonoxximent tal-vuċi jaħdmu kompletament fuq l-apparat u ma jibagħtu xejn. It-telefonati u l-messaġġi deħlin jintwerew u, fakultattivament, jinqraw b'leħen għoli, u mbagħad jintremew: qatt ma jinħażnu u qatt ma jintbagħtu.

🎧  KONTENUT U LIĊENZJAR
Voyager idoqq biss kontenut li l-utent diġà għandu d-dritt idoqq, minn servers li jħaddem hu stess. L-applikazzjoni ma tipprovdi l-ebda kontenut tagħha u l-ebda mezz biex jinkiseb. Ir-responsabbiltà għal-legalità tal-kontenut aċċessat hija kompletament tal-utent.

⚖️  DIVIŻIBBILTÀ
Jekk xi dispożizzjoni ta' dawn it-termini tinstab li mhijiex infurzabbli f'ġurisdizzjoni partikolari, dik id-dispożizzjoni tiġi limitata jew imwarrba sal-inqas ammont meħtieġ, u d-dispożizzjonijiet l-oħra kollha jibqgħu fis-seħħ b'mod sħiħ.

Bl-użu ta' Voyager, kullimkien fid-dinja, l-utent jikkonferma li qara, fehem u aċċetta bla kundizzjoni kull wieħed mit-termini ta' hawn fuq, u jassumi r-responsabbiltà sħiħa u kompleta — kif ukoll ir-riskju kollu — għall-użu tal-applikazzjoni u għal kwalunkwe konsegwenza li tirriżulta minnha.''';
