// Voyager's safety and liability notice, Slovak.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerSk = '''
Voyager je experimentálny palubný panel do auta s otvoreným zdrojovým kódom, udržiavaný komunitou. Spája navigáciu založenú na údajoch OpenStreetMap a protokole Nostr s prehrávaním médií, informáciami o počasí, syntézou reči a voliteľnými telefónnymi funkciami. Stiahnutím, inštaláciou alebo používaním tejto aplikácie používateľ bezvýhradne prijíma všetky nižšie uvedené podmienky, bez územného obmedzenia:

🚗  BEZPEČNOSŤ CESTNEJ PREMÁVKY NA PRVOM MIESTE
Vodič musí mať vždy oči na ceste a dodržiavať všetky platné pravidlá cestnej premávky a osadené dopravné značenie, ktoré má vždy prednosť pred akýmkoľvek pokynom aplikácie. Nikdy neobsluhujte zariadenie počas jazdy; pred vyrazením ho upevnite do schváleného, viditeľného držiaka a nikdy neodvracajte pozornosť od cesty, aby ste s ním pracovali počas jazdy vozidla. V mnohých právnych poriadkoch je držanie zariadenia v ruke za volantom samo osebe priestupkom bez ohľadu na to, čo zariadenie zobrazuje.

🎵  MULTIMÉDIÁ A TELEFONOVANIE POČAS JAZDY
Prehrávanie hudby, čítanie správ nahlas a obsluha hovorov sú funkcie pre pohodlie a poskytujú sa za rovnakých podmienok ako všetko ostatné v aplikácii. Výber hudby, prehliadanie knižnice, čítanie správy na obrazovke alebo vedenie rozhovoru sú kognitívnou záťažou, ktorá znižuje kvalitu vedenia vozidla. Nastavte prehrávanie pred vyrazením a počas jazdy používajte fyzické ovládače na volante namiesto dotykovej obrazovky. Tam, kde miestne právo obmedzuje alebo zakazuje používanie telefónu za volantom, má toto právo prednosť a zodpovedajúce funkcie sa nesmú používať.

⚠️  PREVZATIE RIZIKA — CELOSVETOVO
Používaním Voyageru preberá používateľ v ktorejkoľvek krajine a pod akýmkoľvek právnym poriadkom vedome a dobrovoľne VŠETKY riziká spojené s jeho používaním, okrem iného: dopravné nehody, ujmu na zdraví, smrť, škodu na majetku, poškodenie vozidla, pokuty, správne sankcie, odtiahnutie, zaistenie vozidla, trestnú zodpovednosť alebo akýkoľvek iný následok vyplývajúci priamo či nepriamo zo spoliehania sa na aplikáciu. Používateľ nesie sám plnú zodpovednosť za každé rozhodnutie pri vedení vozidla a navigácii.

🚫  ŽIADNA ZÁRUKA
Voyager sa poskytuje výhradne "TAK, AKO JE" a "PODĽA DOSTUPNOSTI", bez akýchkoľvek výslovných, predpokladaných alebo zákonných záruk — vrátane, bez obmedzenia, záruk presnosti, úplnosti, spoľahlivosti, dostupnosti, predajnosti, vhodnosti na určitý účel a neporušenia práv tretích osôb. Mapové údaje, trasy, rýchlostné limity, radary a informácie o zónach s obmedzenou premávkou pochádzajú z otvorených, komunitou udržiavaných zdrojov (OpenStreetMap, Overpass API), ktoré môžu byť pre ktorúkoľvek krajinu, región či obec neúplné, zastarané alebo nesprávne, kedykoľvek a bez upozornenia. Výhradne používateľ zodpovedá za to, že si pred cestou aj počas nej samostatne overí zákonnosť a prejazdnosť každej navrhnutej trasy voči oficiálnemu miestnemu značeniu a predpisom.

📍  PRESNOSŤ A GPS
Určenie polohy pomocou GPS môže byť nepresné alebo nedostupné. Všetky pokyny, vzdialenosti a upozornenia majú len orientačný charakter a nikdy nesmú byť jediným podkladom rozhodnutia pri vedení vozidla.

🛡️  OBMEDZENIE ZODPOVEDNOSTI
V maximálnom rozsahu povolenom rozhodným právom v ktorejkoľvek jurisdikcii nezodpovedajú vývojári, prispievatelia ani žiadna osoba podieľajúca sa na vytvorení či šírení Voyageru za akékoľvek priame, nepriame, náhodné, následné, osobitné, exemplárne alebo sankčné škody — vrátane ujmy na zdraví, smrti alebo finančnej straty — vzniknuté v súvislosti s používaním alebo nemožnosťou používať aplikáciu, a to ani v prípade, že boli na možnosť takýchto škôd upozornení. Ak jurisdikcia toto obmedzenie úplne alebo sčasti nepripúšťa, zodpovednosť je obmedzená na najmenší rozsah, ktorý tamojšie právo dovoľuje.

🤝  ODŠKODNENIE
Používateľ sa zaväzuje odškodniť vývojárov a prispievateľov a zbaviť ich zodpovednosti za akýkoľvek nárok, škodu, stratu alebo náklad (vrátane nákladov právneho zastúpenia) vzniknutý z jeho používania aplikácie alebo z porušenia týchto podmienok.

🔒  SÚKROMIE A SIEŤOVÉ SLUŽBY
Voyager neprevádzkuje vlastné servery, nezhromažďuje štatistiky používania a neobsahuje žiadnu telemetriu, nie je však offline aplikáciou. Pri použití príslušných funkcií sa súradnice alebo hrubo vymedzené oblasti a IP adresa odosielajú priamo tretím stranám: poskytovateľom plánovania trás (východiskový bod, cieľ a prejazdné body), OpenStreetMap/Nominatim/Overpass (vyhľadávanie, spätné geokódovanie, body záujmu, zóny s obmedzením, limity a radary), Open-Meteo (zaokrúhlené súradnice), serverom mapových dlaždíc a relé Nostr (geohash na úrovni mesta). Dopravné hlásenie zverejňuje v sieti Nostr svoju presnú polohu, čas, obsah a verejný kľúč a je pseudonymné, nie anonymné. Hudobné požiadavky smerujú výhradne na server nakonfigurovaný používateľom; prihlasovacie údaje k nemu sú na zariadení uložené šifrovane. Syntéza aj rozpoznávanie reči bežia úplne na zariadení a nič neodosielajú. Prichádzajúce hovory a správy sa zobrazia a prípadne prečítajú nahlas a potom sa zahodia: nikdy sa neukladajú ani neprenášajú.

🎧  OBSAH A LICENCIE
Voyager prehráva iba obsah, na ktorého prehrávanie je používateľ už oprávnený, zo serverov, ktoré sám prevádzkuje. Aplikácia neposkytuje žiadny vlastný obsah ani spôsob, ako ho získať. Zodpovednosť za zákonnosť sprístupneného obsahu nesie výhradne používateľ.

⚖️  ODDELITEĽNOSŤ USTANOVENÍ
Ak sa niektoré ustanovenie týchto podmienok v danej jurisdikcii ukáže ako nevymáhateľné, bude obmedzené alebo vypustené v najmenšom potrebnom rozsahu a všetky ostatné ustanovenia zostanú v plnej platnosti a účinnosti.

Používaním Voyageru kdekoľvek na svete používateľ potvrdzuje, že si prečítal, porozumel a bezvýhradne prijal každú z vyššie uvedených podmienok, a preberá plnú a úplnú zodpovednosť — ako aj všetky riziká — za používanie aplikácie a za akýkoľvek následok z neho vyplývajúci.''';
