// Voyager's safety and liability notice, Latvian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerLv = '''
Voyager ir eksperimentāls, atvērtā pirmkoda un kopienas uzturēts automobiļa informācijas panelis. Tas apvieno navigāciju, kas balstīta uz OpenStreetMap datiem un Nostr protokolu, ar multivides atskaņošanu, laikapstākļu informāciju, runas sintēzi un neobligātām tālruņa funkcijām. Lejupielādējot, instalējot vai lietojot šo lietotni, lietotājs bez nosacījumiem pieņem visus turpmāk minētos noteikumus bez teritoriāla ierobežojuma:

🚗  VISPIRMS SATIKSMES DROŠĪBA
Vadītājam vienmēr jāraugās uz ceļu un jāievēro visi spēkā esošie satiksmes noteikumi un uzstādītās ceļa zīmes, kurām vienmēr ir prioritāte pār jebkuru lietotnes norādi. Nekad nelietojiet ierīci braukšanas laikā; pirms brauciena nostipriniet to apstiprinātā, redzamā turētājā un nekad nenovērsiet uzmanību no ceļa, lai ar to darbotos, kamēr transportlīdzeklis kustas. Daudzās tiesību sistēmās ierīces turēšana rokās pie stūres pati par sevi ir pārkāpums neatkarīgi no tā, ko ierīce rāda.

🎵  MULTIVIDE UN TĀLRUŅA LIETOŠANA BRAUKŠANAS LAIKĀ
Mūzikas atskaņošana, ziņu nolasīšana un zvanu apstrāde ir ērtību funkcijas, un tās tiek nodrošinātas ar tādiem pašiem noteikumiem kā viss pārējais lietotnē. Mūzikas izvēle, bibliotēkas pārlūkošana, ziņas lasīšana ekrānā vai sarunas vešana ir kognitīva slodze, kas pasliktina braukšanas sniegumu. Iestatiet atskaņošanu pirms brauciena un, kamēr transportlīdzeklis kustas, lietojiet stūres fiziskās vadības pogas, nevis skārienekrānu. Ja vietējie tiesību akti ierobežo vai aizliedz tālruņa lietošanu pie stūres, šie tiesību akti ir noteicošie un attiecīgās funkcijas nedrīkst lietot.

⚠️  RISKA UZŅEMŠANĀS — VISĀ PASAULĒ
Lietojot Voyager jebkurā valstī un jebkuras tiesību sistēmas ietvaros, lietotājs apzināti un brīvprātīgi uzņemas VISUS ar tā lietošanu saistītos riskus, tostarp, bet ne tikai: ceļu satiksmes negadījumus, miesas bojājumus, nāvi, mantisku kaitējumu, transportlīdzekļa bojājumus, naudas sodus, administratīvās sankcijas, evakuāciju, transportlīdzekļa aizturēšanu, kriminālatbildību vai jebkuras citas sekas, kas tieši vai netieši izriet no paļaušanās uz lietotni. Lietotājs vienpersoniski uzņemas pilnu atbildību par katru braukšanas un navigācijas lēmumu.

🚫  BEZ GARANTIJAS
Voyager tiek nodrošināts stingri tāds, "KĀDS TAS IR", un "ATBILSTOŠI PIEEJAMĪBAI", bez jebkādas tiešas, netiešas vai likumā noteiktas garantijas — tostarp bez ierobežojuma garantijas par precizitāti, pilnīgumu, uzticamību, pieejamību, piemērotību pārdošanai, atbilstību konkrētam mērķim un tiesību nepārkāpšanu. Kartogrāfiskie dati, maršruti, ātruma ierobežojumi, ātruma kameras un informācija par ierobežotas satiksmes zonām nāk no atvērtiem, kopienas uzturētiem avotiem (OpenStreetMap, Overpass API), kas jebkurai valstij, reģionam vai pašvaldībai jebkurā brīdī un bez brīdinājuma var būt nepilnīgi, novecojuši vai neprecīzi. Vienīgi lietotājs ir atbildīgs par to, lai pirms brauciena un tā laikā patstāvīgi pārbaudītu jebkura ieteiktā maršruta likumību un izbraucamību attiecībā pret oficiālajām vietējām ceļa zīmēm un noteikumiem.

📍  PRECIZITĀTE UN GPS
GPS pozicionēšana var būt neprecīza vai nepieejama. Visas norādes, attālumi un brīdinājumi ir sniegti tikai orientējoši, un tie nekad nedrīkst būt vienīgais braukšanas lēmuma pamats.

🛡️  ATBILDĪBAS IEROBEŽOJUMS
Cik vien pieļauj piemērojamie tiesību akti jebkurā jurisdikcijā, izstrādātāji, līdzstrādnieki un jebkura puse, kas iesaistīta Voyager izveidē vai izplatīšanā, neatbild par jebkādiem tiešiem, netiešiem, nejaušiem, izrietošiem, īpašiem, brīdinošiem vai soda zaudējumiem — tostarp miesas bojājumiem, nāvi vai finansiāliem zaudējumiem —, kas rodas, lietojot lietotni vai nespējot to lietot, pat ja ir brīdināts par šādu zaudējumu iespējamību. Ja jurisdikcija pilnībā vai daļēji nepieļauj šo ierobežojumu, atbildība tiek ierobežota līdz mazākajam apjomam, ko attiecīgie tiesību akti pieļauj.

🤝  ATLĪDZINĀŠANA
Lietotājs apņemas atlīdzināt un pasargāt izstrādātājus un līdzstrādniekus no jebkādas prasības, kaitējuma, zaudējuma vai izdevuma (tostarp juridiskajām izmaksām), kas izriet no lietotnes lietošanas vai šo noteikumu pārkāpuma.

🔒  PRIVĀTUMS UN TĪKLA PAKALPOJUMI
Voyager neuztur savus serverus, nevāc lietošanas statistiku un nesatur nekādu telemetriju, taču tā nav bezsaistes lietotne. Lietojot attiecīgās funkcijas, koordinātas vai aptuvenas teritorijas un IP adrese tiek nosūtītas tieši trešajām personām: maršrutu pakalpojumu sniedzējiem (sākumpunkts, galamērķis un starppunkti), OpenStreetMap/Nominatim/Overpass (meklēšana, apgrieztā ģeokodēšana, interesantas vietas, ierobežojumu zonas, ierobežojumi un kameras), Open-Meteo (noapaļotas koordinātas), karšu elementu serveriem un Nostr retranslatoriem (pilsētas līmeņa geohash). Satiksmes ziņojums Nostr tīklā publicē savu precīzo atrašanās vietu, laiku, saturu un publisko atslēgu, un tas ir pseidonīms, nevis anonīms. Mūzikas pieprasījumi nonāk tikai lietotāja paša konfigurētajā serverī; tā piekļuves dati ierīcē tiek glabāti šifrēti. Runas sintēze un runas atpazīšana darbojas pilnībā ierīcē un neko nesūta. Ienākošie zvani un ziņas tiek parādītas un pēc izvēles nolasītas skaļi, un pēc tam tiek atmestas: tās nekad netiek saglabātas un nekad netiek pārsūtītas.

🎧  SATURS UN LICENCES
Voyager atskaņo tikai tādu saturu, kuru lietotājam jau ir tiesības atskaņot, no serveriem, kurus viņš pats uztur. Lietotne nepiedāvā savu saturu un nekādu veidu, kā to iegūt. Atbildība par izmantotā satura likumību pilnībā gulstas uz lietotāju.

⚖️  NOTEIKUMU NODALĀMĪBA
Ja kāds šo noteikumu punkts konkrētā jurisdikcijā tiek atzīts par neizpildāmu, tas tiek ierobežots vai svītrots minimāli nepieciešamajā apjomā, un visi pārējie punkti paliek pilnā spēkā.

Lietojot Voyager jebkurā vietā pasaulē, lietotājs apliecina, ka ir izlasījis, sapratis un bez nosacījumiem pieņēmis katru no iepriekš minētajiem noteikumiem, un uzņemas pilnu un visaptverošu atbildību — kā arī visu risku — par lietotnes lietošanu un jebkurām no tās izrietošajām sekām.''';
