// Voyager's safety and liability notice, Swedish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerSv = '''
Voyager är en experimentell instrumentpanel för bilen, med öppen källkod och underhållen av gemenskapen. Den kombinerar navigering baserad på OpenStreetMap-data och Nostr-protokollet med medieuppspelning, väderinformation, talsyntes och valfria telefonifunktioner. Genom att ladda ner, installera eller använda denna app godtar användaren villkorslöst samtliga nedanstående villkor, utan territoriell begränsning:

🚗  TRAFIKSÄKERHETEN FÖRST
Föraren ska alltid hålla blicken på vägen och följa alla gällande trafikregler och all uppsatt vägmärkning, som alltid har företräde framför varje anvisning från appen. Använd aldrig enheten under körning; fäst den före avfärd i en godkänd, synlig hållare och vänd aldrig uppmärksamheten från vägen för att interagera med den när fordonet är i rörelse. I många rättsordningar är det i sig en förseelse att hantera en enhet vid ratten, oavsett vad enheten visar.

🎵  MEDIA OCH TELEFONI UNDER KÖRNING
Musikuppspelning, uppläsning av meddelanden och samtalshantering är bekvämlighetsfunktioner och tillhandahålls på samma villkor som allt annat i appen. Att välja musik, bläddra i ett bibliotek, läsa ett meddelande på skärmen eller föra ett samtal är alla kognitiva belastningar som försämrar körförmågan. Ställ in uppspelningen före avfärd och använd rattens fysiska reglage i stället för pekskärmen så snart fordonet är i rörelse. Där lokal lag begränsar eller förbjuder telefonanvändning vid ratten har den lagen företräde och motsvarande funktioner får inte användas.

⚠️  RISKÖVERTAGANDE — VÄRLDEN ÖVER
Genom att använda Voyager övertar användaren, i varje land och under varje rättsordning, medvetet och frivilligt ALLA risker förknippade med användningen, inklusive men inte begränsat till: trafikolyckor, personskada, dödsfall, sakskada, fordonsskada, böter, administrativa sanktioner, bortbogsering, beslag, straffrättsligt ansvar eller varje annan följd som direkt eller indirekt uppstår av att förlita sig på appen. Användaren bär ensam det fulla ansvaret för varje kör- och navigeringsbeslut.

🚫  INGEN GARANTI
Voyager tillhandahålls strikt "I BEFINTLIGT SKICK" och "I MÅN AV TILLGÅNG", utan någon som helst garanti, uttrycklig, underförstådd eller lagstadgad — inklusive, utan begränsning, garantier om riktighet, fullständighet, tillförlitlighet, tillgänglighet, säljbarhet, lämplighet för visst ändamål och frihet från intrång. Kartdata, rutter, hastighetsgränser, fartkameror och uppgifter om miljözoner och trafikbegränsade områden kommer från öppna källor som underhålls av gemenskapen (OpenStreetMap, Overpass API) och kan vara ofullständiga, inaktuella eller felaktiga för vilket land, vilken region eller vilken kommun som helst, när som helst och utan förvarning. Användaren ansvarar ensam för att på egen hand, före och under resan, kontrollera att en föreslagen rutt är tillåten och framkomlig enligt officiell lokal skyltning och lokala föreskrifter.

📍  NOGGRANNHET OCH GPS
GPS-positionering kan vara felaktig eller otillgänglig. Alla anvisningar, avstånd och varningar tillhandahålls endast som vägledning och får aldrig utgöra den enda grunden för ett körbeslut.

🛡️  ANSVARSBEGRÄNSNING
I den utsträckning som tillämplig lag i varje jurisdiktion medger ansvarar utvecklarna, bidragsgivarna och varje part som medverkat till att skapa eller sprida Voyager inte för några direkta, indirekta, tillfälliga, följd-, särskilda, exemplariska eller straffande skador av något slag — inklusive personskada, dödsfall eller ekonomisk förlust — som uppstår genom användningen av eller oförmågan att använda appen, även om de underrättats om risken för sådana skador. Där en jurisdiktion inte tillåter hela eller delar av denna begränsning är ansvaret begränsat till minsta möjliga omfattning som lagen där medger.

🤝  SKADESLÖSHET
Användaren åtar sig att hålla utvecklarna och bidragsgivarna skadeslösa från varje krav, skada, förlust eller kostnad (inklusive juridiska kostnader) som uppstår genom användarens användning av appen eller brott mot dessa villkor.

🔒  INTEGRITET OCH NÄTVERKSTJÄNSTER
Voyager driver inga egna servrar, samlar ingen användningsstatistik och innehåller ingen som helst telemetri, men den är inte en offline-app. När berörda funktioner används skickas koordinater eller grova områden samt IP-adressen direkt till tredje part: ruttleverantörer (start, mål och delmål), OpenStreetMap/Nominatim/Overpass (sökning, omvänd geokodning, intressepunkter, begränsade zoner, hastighetsgränser och fartkameror), Open-Meteo (avrundade koordinater), kartrutsservrar och Nostr-reläer (geohash på stadsnivå). En trafikrapport publicerar sin exakta position, tidpunkt, sitt innehåll och sin publika nyckel på Nostr och är pseudonym, inte anonym. Musikförfrågningar går enbart till den server användaren själv har konfigurerat; inloggningsuppgifterna till den lagras krypterade på enheten. Talsyntes och taligenkänning körs helt på enheten och skickar ingenting. Inkommande samtal och meddelanden visas och läses eventuellt upp, och kasseras därefter: de sparas aldrig och överförs aldrig.

🎧  INNEHÅLL OCH LICENSER
Voyager spelar endast upp material som användaren redan har rätt att spela upp, från servrar som användaren själv driver. Appen tillhandahåller inget eget innehåll och inget sätt att skaffa något. Ansvaret för lagligheten hos det material som används vilar helt på användaren.

⚖️  OGILTIGHET AV ENSKILD BESTÄMMELSE
Om någon bestämmelse i dessa villkor befinns icke verkställbar i en viss jurisdiktion ska den begränsas eller utgå i minsta nödvändiga omfattning, och samtliga övriga bestämmelser ska fortsatt gälla fullt ut.

Genom att använda Voyager, var som helst i världen, bekräftar användaren att varje villkor ovan har lästs, förståtts och godtagits villkorslöst, och tar det fulla och hela ansvaret — och hela risken — för användningen av applikationen och för varje följd av den.''';
