// Voyager's safety and liability notice, Hungarian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerHu = '''
A Voyager egy kísérleti, nyílt forráskódú, közösség által karbantartott autós műszerfal. Az OpenStreetMap adatain és a Nostr protokollon alapuló navigációt médialejátszással, időjárási információkkal, beszédszintézissel és opcionális telefonálási funkciókkal egyesíti. Az alkalmazás letöltésével, telepítésével vagy használatával a felhasználó feltétel nélkül elfogadja az alábbi feltételek mindegyikét, területi korlátozás nélkül:

🚗  ELŐSZÖR A KÖZLEKEDÉSBIZTONSÁG
A vezetőnek mindig az úton kell tartania a tekintetét, és be kell tartania minden hatályos közlekedési szabályt és a kihelyezett jelzéseket, amelyek mindig elsőbbséget élveznek az alkalmazás bármely utasításával szemben. Soha ne kezelje a készüléket vezetés közben; indulás előtt rögzítse jóváhagyott, jól látható tartóba, és mozgó járműnél soha ne fordítsa el a figyelmét az útról, hogy azzal foglalkozzon. Számos jogrendszerben a készülék kézben tartása a volánnál önmagában szabálysértés, függetlenül attól, mit mutat a kijelző.

🎵  MÉDIA ÉS TELEFONÁLÁS VEZETÉS KÖZBEN
A zenelejátszás, az üzenetek felolvasása és a hívások kezelése kényelmi funkciók, és ugyanolyan feltételekkel érhetők el, mint az alkalmazás minden más része. A zene kiválasztása, a könyvtár böngészése, egy üzenet elolvasása a képernyőn vagy egy beszélgetés folytatása egyaránt olyan kognitív terhelés, amely rontja a vezetési teljesítményt. Állítsa be a lejátszást indulás előtt, és mozgó járműnél a kormányon lévő fizikai kezelőszerveket használja az érintőképernyő helyett. Ahol a helyi jog korlátozza vagy tiltja a telefon vezetés közbeni használatát, ott az a jog az irányadó, és a megfelelő funkciók nem használhatók.

⚠️  KOCKÁZATVÁLLALÁS — VILÁGSZERTE
A Voyager használatával a felhasználó bármely országban és bármely jogrendszer alatt tudatosan és önként vállalja a használattal járó MINDEN kockázatot, ideértve, de nem kizárólag: közúti baleseteket, személyi sérülést, halált, vagyoni kárt, járműkárt, bírságokat, közigazgatási szankciókat, elszállítást, jármű lefoglalását, büntetőjogi felelősséget vagy bármely más következményt, amely közvetlenül vagy közvetve az alkalmazásra való támaszkodásból ered. A felhasználó egyedül viseli a teljes felelősséget minden vezetési és navigációs döntéséért.

🚫  SEMMILYEN SZAVATOSSÁG
A Voyager szigorúan "ADOTT ÁLLAPOTBAN" és "ELÉRHETŐSÉG SZERINT" kerül átadásra, bármiféle kifejezett, hallgatólagos vagy törvényi szavatosság nélkül — ideértve korlátozás nélkül a pontosságra, teljességre, megbízhatóságra, rendelkezésre állásra, forgalomképességre, adott célra való alkalmasságra és jogsértés-mentességre vonatkozó szavatosságot. A térképadatok, útvonalak, sebességkorlátozások, traffipaxok és a korlátozott forgalmú övezetekre vonatkozó adatok nyílt, közösség által karbantartott forrásokból (OpenStreetMap, Overpass API) származnak, amelyek bármely ország, régió vagy település esetében, bármikor és előzetes értesítés nélkül hiányosak, elavultak vagy pontatlanok lehetnek. Kizárólag a felhasználó felelős azért, hogy az utazás előtt és közben önállóan ellenőrizze bármely javasolt útvonal jogszerűségét és járhatóságát a hivatalos helyi jelzések és előírások alapján.

📍  PONTOSSÁG ÉS GPS
A GPS-helymeghatározás pontatlan vagy elérhetetlen lehet. Minden útmutatás, távolság és figyelmeztetés kizárólag tájékoztató jellegű, és soha nem szolgálhat egyetlen alapként egy vezetési döntéshez.

🛡️  FELELŐSSÉGKORLÁTOZÁS
Az egyes joghatóságokban alkalmazandó jog által megengedett legnagyobb mértékben a fejlesztők, a közreműködők és a Voyager létrehozásában vagy terjesztésében részt vevő bármely fél nem felel semmilyen közvetlen, közvetett, járulékos, következményes, különleges, példázó vagy büntető jellegű kárért — ideértve a személyi sérülést, a halált vagy a pénzügyi veszteséget —, amely az alkalmazás használatából vagy a használat lehetetlenségéből ered, még akkor sem, ha az ilyen károk lehetőségére figyelmeztették őket. Ahol egy joghatóság e korlátozást egészben vagy részben nem engedi meg, a felelősség az ott jogszabályban megengedett legkisebb mértékre korlátozódik.

🤝  KÁRTALANÍTÁS
A felhasználó vállalja, hogy kártalanítja és mentesíti a fejlesztőket és a közreműködőket minden olyan igény, kár, veszteség vagy költség (ideértve a jogi költségeket) alól, amely az alkalmazás általa történő használatából vagy a jelen feltételek megsértéséből ered.

🔒  ADATVÉDELEM ÉS HÁLÓZATI SZOLGÁLTATÁSOK
A Voyager nem üzemeltet saját szervereket, nem gyűjt használati statisztikát, és semmilyen telemetriát nem tartalmaz, de nem offline alkalmazás. Az érintett funkciók használatakor koordináták vagy durva területi adatok, valamint az IP-cím közvetlenül harmadik feleknek kerülnek elküldésre: útvonaltervező szolgáltatóknak (kiindulópont, célpont és köztes pontok), az OpenStreetMapnek/Nominatimnak/Overpassnak (keresés, fordított geokódolás, érdekes helyek, korlátozott övezetek, sebességhatárok és kamerák), az Open-Meteónak (kerekített koordináták), térképcsempe-kiszolgálóknak és Nostr-reléknek (városi szintű geohash). Egy forgalmi bejelentés a Nostr hálózaton közzéteszi pontos helyzetét, idejét, tartalmát és nyilvános kulcsát, tehát álnéven történik, nem névtelenül. A zenei kérések kizárólag a felhasználó által beállított szerverhez jutnak el; annak hitelesítő adatai titkosítva tárolódnak a készüléken. A beszédszintézis és a beszédfelismerés teljes egészében a készüléken fut, és semmit nem küld el. A bejövő hívások és üzenetek megjelennek, opcionálisan felolvasásra kerülnek, majd eldobódnak: soha nem kerülnek tárolásra és soha nem kerülnek továbbításra.

🎧  TARTALOM ÉS LICENCEK
A Voyager kizárólag olyan tartalmat játszik le, amelynek lejátszására a felhasználónak már joga van, az általa üzemeltetett szerverekről. Az alkalmazás nem kínál saját tartalmat, és nem biztosít semmilyen módot annak beszerzésére. Az elért tartalom jogszerűségéért a felelősség teljes egészében a felhasználót terheli.

⚖️  RÉSZLEGES ÉRVÉNYTELENSÉG
Ha a jelen feltételek bármely rendelkezése egy adott joghatóságban végrehajthatatlannak bizonyul, azt a szükséges legkisebb mértékben korlátozni kell vagy el kell hagyni, és az összes többi rendelkezés teljes egészében hatályban marad.

A Voyager használatával a világ bármely pontján a felhasználó megerősíti, hogy a fenti feltételek mindegyikét elolvasta, megértette és feltétel nélkül elfogadta, és teljes és maradéktalan felelősséget — valamint minden kockázatot — vállal az alkalmazás használatáért és annak bármely következményéért.''';
