// Voyager's safety and liability notice, Spanish.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerEs = '''
Voyager es un panel de a bordo experimental, de código abierto y mantenido por la comunidad. Combina una navegación basada en los datos de OpenStreetMap y en el protocolo Nostr con reproducción multimedia, información meteorológica, síntesis de voz y funciones telefónicas opcionales. Al descargar, instalar o utilizar esta aplicación, el usuario acepta incondicionalmente todos los términos siguientes, sin limitación de territorio:

🚗  LA SEGURIDAD VIAL ANTE TODO
El conductor debe mantener siempre la vista en la carretera y cumplir todas las normas de circulación y la señalización existente, que prevalecen siempre sobre cualquier indicación de la aplicación. No manipule nunca el dispositivo mientras conduce; fíjelo antes de salir en un soporte homologado y visible, y no aparte nunca la atención de la carretera para interactuar con él con el vehículo en movimiento. En muchos ordenamientos, manipular un dispositivo al volante constituye por sí mismo una infracción, con independencia de lo que el dispositivo muestre.

🎵  MULTIMEDIA Y TELEFONÍA DURANTE LA CONDUCCIÓN
La reproducción de música, la lectura de mensajes y la gestión de llamadas son funciones de comodidad y se ofrecen en las mismas condiciones que el resto de la aplicación. Elegir música, explorar una biblioteca, leer un mensaje en pantalla o mantener una conversación son cargas cognitivas que reducen el rendimiento al volante. Configure la reproducción antes de salir y utilice los mandos físicos del volante en lugar de la pantalla táctil siempre que el vehículo esté en movimiento. Cuando la legislación local restrinja o prohíba el uso del teléfono al volante, dicha legislación prevalece y las funciones correspondientes no deben utilizarse.

⚠️  ASUNCIÓN DE RIESGOS — EN TODO EL MUNDO
Al utilizar Voyager, en cualquier país y bajo cualquier ordenamiento jurídico, el usuario asume consciente y voluntariamente TODOS los riesgos asociados a su uso, incluidos, entre otros: accidentes de tráfico, lesiones personales, muerte, daños materiales, daños al vehículo, multas, sanciones administrativas, retirada del vehículo, inmovilización, responsabilidad penal o cualquier otra consecuencia derivada directa o indirectamente de la confianza depositada en la aplicación. El usuario es el único plenamente responsable de cada decisión de conducción y de navegación.

🚫  SIN GARANTÍA
Voyager se proporciona estrictamente "TAL CUAL" y "SEGÚN DISPONIBILIDAD", sin garantía de ningún tipo, expresa, implícita o legal, incluidas, sin limitación, las garantías de exactitud, integridad, fiabilidad, disponibilidad, comerciabilidad, idoneidad para un fin determinado y no infracción. Los datos cartográficos, las rutas, los límites de velocidad, los radares y la información sobre zonas de tráfico restringido proceden de fuentes abiertas mantenidas por la comunidad (OpenStreetMap, Overpass API) que pueden ser incompletas, estar desactualizadas o ser inexactas para cualquier país, región o municipio, en cualquier momento y sin previo aviso. El usuario es el único responsable de verificar por su cuenta, antes y durante el viaje, la legalidad y la accesibilidad de cualquier ruta sugerida frente a la señalización y la normativa locales oficiales.

📍  PRECISIÓN Y GPS
El posicionamiento GPS puede ser impreciso o no estar disponible. Todas las indicaciones, distancias y avisos se ofrecen únicamente a título orientativo y nunca deben constituir la única base de una decisión de conducción.

🛡️  LIMITACIÓN DE RESPONSABILIDAD
En la máxima medida permitida por la legislación aplicable en cualquier jurisdicción, los desarrolladores, los colaboradores y cualquier parte implicada en la creación o distribución de Voyager no serán responsables de daños directos, indirectos, incidentales, consecuentes, especiales, ejemplares o punitivos de ningún tipo —incluidas lesiones personales, muerte o pérdidas económicas— derivados del uso o de la imposibilidad de usar la aplicación, incluso si se les hubiera advertido de la posibilidad de tales daños. Cuando una jurisdicción no permita esta limitación en todo o en parte, la responsabilidad quedará limitada en la menor medida permitida por la ley aplicable.

🤝  INDEMNIZACIÓN
El usuario se compromete a indemnizar y mantener indemnes a los desarrolladores y colaboradores frente a cualquier reclamación, daño, pérdida o gasto (incluidos los honorarios legales) derivados de su uso de la aplicación o del incumplimiento de estos términos.

🔒  PRIVACIDAD Y SERVICIOS DE RED
Voyager no dispone de servidores propios, no recopila estadísticas de uso y no contiene telemetría de ningún tipo, pero no es una aplicación sin conexión. Cuando se utilizan las funciones correspondientes, se envían directamente a terceros coordenadas o áreas aproximadas y la dirección IP: proveedores de rutas (origen, destino y paradas), OpenStreetMap/Nominatim/Overpass (búsqueda, geocodificación inversa, puntos de interés, zonas restringidas, límites y radares), Open-Meteo (coordenadas redondeadas), servidores de teselas cartográficas y relés Nostr (geohash a escala de ciudad). Un aviso de tráfico publica en Nostr su posición exacta, la hora, el contenido y la clave pública: es seudónimo, no anónimo. Las peticiones de música se dirigen únicamente al servidor configurado por el usuario; sus credenciales se almacenan cifradas en el dispositivo. La síntesis y el reconocimiento de voz funcionan íntegramente en el dispositivo y no envían nada. Las llamadas y los mensajes entrantes se muestran y, opcionalmente, se leen en voz alta, y después se descartan: nunca se guardan ni se transmiten.

🎧  CONTENIDOS Y LICENCIAS
Voyager reproduce únicamente contenidos que el usuario ya tiene derecho a reproducir, desde servidores gestionados por él mismo. La aplicación no ofrece contenidos propios ni medio alguno para obtenerlos. La responsabilidad sobre la licitud de los contenidos consultados recae por completo en el usuario.

⚖️  DIVISIBILIDAD
Si alguna disposición de estos términos resultara inaplicable en una jurisdicción determinada, se limitará o suprimirá en la medida mínima necesaria, y todas las demás disposiciones mantendrán plena vigencia y efecto.

Al utilizar Voyager, en cualquier lugar del mundo, el usuario confirma haber leído, comprendido y aceptado incondicionalmente cada uno de los términos anteriores, y asume la plena y completa responsabilidad —y todo el riesgo— del uso de la aplicación y de cualquier consecuencia derivada del mismo.''';
