// Voyager's safety and liability notice, Portuguese.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerPt = '''
O Voyager é um painel de bordo experimental, de código aberto e mantido pela comunidade. Combina uma navegação baseada nos dados do OpenStreetMap e no protocolo Nostr com reprodução multimédia, informação meteorológica, síntese de voz e funções telefónicas opcionais. Ao descarregar, instalar ou utilizar esta aplicação, o utilizador aceita incondicionalmente todos os termos seguintes, sem limitação de território:

🚗  A SEGURANÇA RODOVIÁRIA EM PRIMEIRO LUGAR
O condutor deve manter sempre os olhos na estrada e cumprir todas as regras de trânsito e a sinalização existente, que prevalecem sempre sobre qualquer indicação da aplicação. Nunca opere o dispositivo enquanto conduz; fixe-o antes de partir num suporte homologado e visível e nunca desvie a atenção da estrada para interagir com ele com o veículo em movimento. Em muitas jurisdições, manusear um dispositivo ao volante constitui por si só uma contraordenação, independentemente do que o dispositivo mostra.

🎵  MULTIMÉDIA E TELEFONIA DURANTE A CONDUÇÃO
A reprodução de música, a leitura de mensagens e a gestão de chamadas são funções de conveniência e são fornecidas nas mesmas condições que tudo o resto na aplicação. Escolher música, percorrer uma biblioteca, ler uma mensagem no ecrã ou manter uma conversa são cargas cognitivas que reduzem o desempenho na condução. Configure a reprodução antes de partir e utilize os comandos físicos do volante em vez do ecrã tátil sempre que o veículo estiver em movimento. Onde a lei local restringir ou proibir o uso do telefone ao volante, essa lei prevalece e as funções correspondentes não devem ser utilizadas.

⚠️  ASSUNÇÃO DE RISCO — EM TODO O MUNDO
Ao utilizar o Voyager, em qualquer país e sob qualquer ordenamento jurídico, o utilizador assume consciente e voluntariamente TODOS os riscos associados à sua utilização, incluindo, mas não se limitando a: acidentes de viação, lesões pessoais, morte, danos materiais, danos no veículo, coimas, sanções administrativas, reboque, apreensão, responsabilidade criminal ou qualquer outra consequência decorrente direta ou indiretamente da confiança depositada na aplicação. O utilizador é o único e integralmente responsável por cada decisão de condução e de navegação.

🚫  SEM GARANTIA
O Voyager é fornecido estritamente "TAL COMO ESTÁ" e "CONFORME DISPONÍVEL", sem qualquer garantia, expressa, implícita ou legal — incluindo, sem limitação, garantias de exatidão, integridade, fiabilidade, disponibilidade, comerciabilidade, adequação a uma finalidade específica e não violação de direitos. Os dados cartográficos, os percursos, os limites de velocidade, os radares e a informação sobre zonas de trânsito condicionado provêm de fontes abertas mantidas pela comunidade (OpenStreetMap, Overpass API) que podem estar incompletas, desatualizadas ou incorretas para qualquer país, região ou município, a qualquer momento e sem aviso prévio. Cabe exclusivamente ao utilizador verificar de forma autónoma, antes e durante a viagem, a legalidade e a acessibilidade de qualquer percurso sugerido face à sinalização e à regulamentação locais oficiais.

📍  RIGOR E GPS
O posicionamento GPS pode ser impreciso ou estar indisponível. Todas as indicações, distâncias e alertas são fornecidos apenas a título orientativo e nunca devem constituir a única base de uma decisão de condução.

🛡️  LIMITAÇÃO DE RESPONSABILIDADE
Na máxima medida permitida pela lei aplicável em qualquer jurisdição, os programadores, os contribuidores e qualquer parte envolvida na criação ou distribuição do Voyager não serão responsáveis por danos diretos, indiretos, incidentais, consequenciais, especiais, exemplares ou punitivos de qualquer natureza — incluindo lesões pessoais, morte ou perdas financeiras — decorrentes da utilização ou da impossibilidade de utilizar a aplicação, mesmo que avisados da possibilidade de tais danos. Quando uma jurisdição não permitir esta limitação, no todo ou em parte, a responsabilidade fica limitada à menor medida permitida por essa lei.

🤝  INDEMNIZAÇÃO
O utilizador compromete-se a indemnizar e a isentar de responsabilidade os programadores e os contribuidores relativamente a qualquer reclamação, dano, perda ou despesa (incluindo custos legais) decorrente da sua utilização da aplicação ou da violação destes termos.

🔒  PRIVACIDADE E SERVIÇOS DE REDE
O Voyager não opera servidores próprios, não recolhe estatísticas de utilização e não contém qualquer forma de telemetria, mas não é uma aplicação offline. Quando as funções em causa são utilizadas, coordenadas ou áreas aproximadas e o endereço IP são enviados diretamente a terceiros: fornecedores de cálculo de percursos (origem, destino e pontos intermédios), OpenStreetMap/Nominatim/Overpass (pesquisa, geocodificação inversa, pontos de interesse, zonas condicionadas, limites e radares), Open-Meteo (coordenadas arredondadas), servidores de mosaicos cartográficos e relés Nostr (geohash ao nível da cidade). Uma comunicação de trânsito publica no Nostr a sua posição exata, a hora, o conteúdo e a chave pública, sendo pseudónima e não anónima. Os pedidos de música destinam-se apenas ao servidor configurado pelo utilizador; as credenciais desse servidor são guardadas cifradas no dispositivo. A síntese e o reconhecimento de voz funcionam inteiramente no dispositivo e não enviam nada. As chamadas e mensagens recebidas são apresentadas e, opcionalmente, lidas em voz alta, sendo depois descartadas: nunca são guardadas nem transmitidas.

🎧  CONTEÚDOS E LICENCIAMENTO
O Voyager reproduz apenas conteúdos que o utilizador já tem o direito de reproduzir, a partir de servidores por si geridos. A aplicação não disponibiliza conteúdos próprios nem qualquer meio de os obter. A responsabilidade pela licitude dos conteúdos acedidos é inteiramente do utilizador.

⚖️  DIVISIBILIDADE
Se alguma disposição destes termos for considerada inaplicável numa determinada jurisdição, será limitada ou eliminada na medida mínima necessária, mantendo-se todas as restantes disposições em pleno vigor e efeito.

Ao utilizar o Voyager, em qualquer parte do mundo, o utilizador confirma ter lido, compreendido e aceite incondicionalmente cada um dos termos acima, e assume a total e completa responsabilidade — e todo o risco — pela utilização da aplicação e por qualquer consequência dela decorrente.''';
