// Voyager's safety and liability notice, Czech.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerCs = '''
Voyager je experimentální palubní panel do auta s otevřeným zdrojovým kódem, udržovaný komunitou. Spojuje navigaci založenou na datech OpenStreetMap a protokolu Nostr s přehráváním médií, informacemi o počasí, syntézou řeči a volitelnými telefonními funkcemi. Stažením, instalací nebo používáním této aplikace uživatel bezvýhradně přijímá všechny níže uvedené podmínky, bez územního omezení:

🚗  BEZPEČNOST PROVOZU PŘEDEVŠÍM
Řidič musí mít vždy oči na silnici a dodržovat všechna platná pravidla provozu a osazené dopravní značení, které má vždy přednost před jakýmkoli pokynem aplikace. Nikdy neobsluhujte zařízení za jízdy; před vyjetím je upevněte do schváleného, viditelného držáku a nikdy neodvracejte pozornost od silnice, abyste s ním pracovali za jízdy vozidla. V mnoha právních řádech je držení zařízení v ruce za volantem samo o sobě přestupkem bez ohledu na to, co zařízení zobrazuje.

🎵  MULTIMÉDIA A TELEFONOVÁNÍ ZA JÍZDY
Přehrávání hudby, předčítání zpráv a obsluha hovorů jsou funkce pro pohodlí a jsou poskytovány za stejných podmínek jako vše ostatní v aplikaci. Výběr hudby, procházení knihovny, čtení zprávy na obrazovce nebo vedení hovoru jsou kognitivní zátěží, která snižuje kvalitu řízení. Nastavte přehrávání před vyjetím a za jízdy používejte fyzická tlačítka na volantu namísto dotykové obrazovky. Tam, kde místní právo omezuje nebo zakazuje používání telefonu za volantem, má toto právo přednost a odpovídající funkce nesmějí být používány.

⚠️  PŘEVZETÍ RIZIKA — CELOSVĚTOVĚ
Používáním Voyageru přebírá uživatel v jakékoli zemi a pod jakýmkoli právním řádem vědomě a dobrovolně VEŠKERÁ rizika spojená s jeho užíváním, mimo jiné: dopravní nehody, újmu na zdraví, smrt, škodu na majetku, poškození vozidla, pokuty, správní sankce, odtah, zabavení vozidla, trestní odpovědnost nebo jakýkoli jiný následek vyplývající přímo či nepřímo ze spoléhání se na aplikaci. Uživatel nese sám plnou odpovědnost za každé rozhodnutí při řízení a navigaci.

🚫  ŽÁDNÁ ZÁRUKA
Voyager je poskytován výhradně "TAK, JAK JE" a "PODLE DOSTUPNOSTI", bez jakýchkoli záruk výslovných, předpokládaných nebo zákonných — včetně, bez omezení, záruk přesnosti, úplnosti, spolehlivosti, dostupnosti, prodejnosti, vhodnosti pro určitý účel a neporušení práv třetích osob. Mapová data, trasy, rychlostní limity, radary a informace o zónách s omezeným provozem pocházejí z otevřených, komunitou udržovaných zdrojů (OpenStreetMap, Overpass API), které mohou být pro kteroukoli zemi, region či obec neúplné, zastaralé nebo nesprávné, kdykoli a bez upozornění. Výhradně uživatel odpovídá za to, že si před cestou i během ní samostatně ověří zákonnost a průjezdnost každé navržené trasy vůči oficiálnímu místnímu značení a předpisům.

📍  PŘESNOST A GPS
Určení polohy pomocí GPS může být nepřesné nebo nedostupné. Veškeré pokyny, vzdálenosti a upozornění mají pouze orientační charakter a nikdy nesmějí být jediným podkladem rozhodnutí při řízení.

🛡️  OMEZENÍ ODPOVĚDNOSTI
V maximálním rozsahu povoleném rozhodným právem v kterékoli jurisdikci neodpovídají vývojáři, přispěvatelé ani jakákoli osoba podílející se na vytvoření či šíření Voyageru za jakékoli přímé, nepřímé, nahodilé, následné, zvláštní, exemplární nebo sankční škody — včetně újmy na zdraví, smrti nebo finanční ztráty — vzniklé v souvislosti s užíváním nebo nemožností užívat aplikaci, a to ani v případě, že byli na možnost takových škod upozorněni. Pokud jurisdikce toto omezení zcela nebo zčásti nepřipouští, je odpovědnost omezena na nejmenší rozsah, který tamní právo dovoluje.

🤝  ODŠKODNĚNÍ
Uživatel se zavazuje odškodnit vývojáře a přispěvatele a zbavit je odpovědnosti za jakýkoli nárok, škodu, ztrátu nebo náklad (včetně nákladů právního zastoupení) vzniklý z jeho užívání aplikace nebo z porušení těchto podmínek.

🔒  SOUKROMÍ A SÍŤOVÉ SLUŽBY
Voyager neprovozuje vlastní servery, neshromažďuje statistiky užívání a neobsahuje žádnou telemetrii, není však offline aplikací. Při použití příslušných funkcí jsou souřadnice nebo hrubě vymezené oblasti a IP adresa odesílány přímo třetím stranám: poskytovatelům plánování tras (výchozí bod, cíl a průjezdní body), OpenStreetMap/Nominatim/Overpass (vyhledávání, zpětné geokódování, body zájmu, zóny s omezením, limity a radary), Open-Meteo (zaokrouhlené souřadnice), serverům mapových dlaždic a relé Nostr (geohash na úrovni města). Dopravní hlášení zveřejňuje v síti Nostr svou přesnou polohu, čas, obsah a veřejný klíč a je pseudonymní, nikoli anonymní. Hudební požadavky směřují výhradně na server nakonfigurovaný uživatelem; přihlašovací údaje k němu jsou na zařízení uloženy šifrovaně. Syntéza i rozpoznávání řeči běží zcela na zařízení a nic neodesílají. Příchozí hovory a zprávy se zobrazí a případně přečtou nahlas a poté jsou zahozeny: nikdy se neukládají ani nepřenášejí.

🎧  OBSAH A LICENCE
Voyager přehrává pouze obsah, k jehož přehrávání je uživatel již oprávněn, ze serverů, které sám provozuje. Aplikace neposkytuje žádný vlastní obsah ani jakýkoli způsob jeho získání. Odpovědnost za zákonnost zpřístupněného obsahu nese výhradně uživatel.

⚖️  ODDĚLITELNOST USTANOVENÍ
Bude-li některé ustanovení těchto podmínek v dané jurisdikci shledáno nevymahatelným, bude omezeno nebo vypuštěno v nejmenším nutném rozsahu a všechna ostatní ustanovení zůstanou plně v platnosti a účinnosti.

Používáním Voyageru kdekoli na světě uživatel potvrzuje, že si přečetl, porozuměl a bezvýhradně přijal každou z výše uvedených podmínek, a přebírá plnou a úplnou odpovědnost — i veškeré riziko — za užívání aplikace a za jakýkoli následek z něj plynoucí.''';
