// Voyager's safety and liability notice, French.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerFr = '''
Voyager est un tableau de bord embarqué expérimental, open source et maintenu par la communauté. Il associe une navigation fondée sur les données OpenStreetMap et le protocole Nostr à la lecture de médias, à des informations météorologiques, à la synthèse vocale et à des fonctions téléphoniques facultatives. En téléchargeant, en installant ou en utilisant cette application, l'utilisateur accepte sans réserve l'ensemble des conditions ci-dessous, sans limitation de territoire :

🚗  LA SÉCURITÉ ROUTIÈRE AVANT TOUT
Le conducteur doit garder les yeux sur la route en permanence et respecter l'ensemble des règles de circulation et de la signalisation en place, qui priment toujours sur toute indication de l'application. N'utilisez jamais l'appareil en conduisant ; fixez-le avant le départ sur un support homologué et visible, et ne détournez jamais votre attention de la route pour interagir avec lui lorsque le véhicule roule. Dans de nombreuses juridictions, manipuler un appareil au volant constitue en soi une infraction, quel que soit son contenu affiché.

🎵  MÉDIAS ET TÉLÉPHONIE PENDANT LA CONDUITE
La lecture de musique, la lecture des messages et la gestion des appels sont des fonctions de confort, fournies aux mêmes conditions que le reste de l'application. Choisir de la musique, parcourir une bibliothèque, lire un message à l'écran ou tenir une conversation constituent autant de charges cognitives qui dégradent la conduite. Configurez la lecture avant de partir et utilisez les commandes physiques au volant plutôt que l'écran tactile dès que le véhicule est en mouvement. Lorsque la loi locale limite ou interdit l'usage du téléphone au volant, cette loi prévaut et les fonctions correspondantes ne doivent pas être utilisées.

⚠️  ACCEPTATION DES RISQUES — DANS LE MONDE ENTIER
En utilisant Voyager, dans quelque pays et sous quelque régime juridique que ce soit, l'utilisateur assume sciemment et volontairement TOUS les risques liés à cet usage, y compris, sans s'y limiter : accidents de la circulation, blessures corporelles, décès, dommages matériels, dommages au véhicule, amendes, sanctions administratives, mise en fourrière, immobilisation, responsabilité pénale, ou toute autre conséquence découlant directement ou indirectement de la confiance accordée à l'application. L'utilisateur est seul et pleinement responsable de chaque décision de conduite et de navigation.

🚫  ABSENCE DE GARANTIE
Voyager est fourni strictement « EN L'ÉTAT » et « SELON DISPONIBILITÉ », sans garantie d'aucune sorte, expresse, implicite ou légale — y compris, sans limitation, les garanties d'exactitude, d'exhaustivité, de fiabilité, de disponibilité, de qualité marchande, d'adéquation à un usage particulier et d'absence de contrefaçon. Les données cartographiques, les itinéraires, les limitations de vitesse, les radars et les informations sur les zones à circulation restreinte proviennent de sources ouvertes et communautaires (OpenStreetMap, Overpass API) susceptibles d'être incomplètes, obsolètes ou inexactes pour tout pays, toute région ou toute commune, à tout moment et sans préavis. Il incombe au seul utilisateur de vérifier par lui-même, avant et pendant le trajet, la légalité et l'accessibilité de tout itinéraire proposé au regard de la signalisation et de la réglementation locales officielles.

📍  PRÉCISION ET GPS
Le positionnement GPS peut être imprécis ou indisponible. Toutes les indications, distances et alertes sont fournies à titre purement indicatif et ne doivent jamais constituer le seul fondement d'une décision de conduite.

🛡️  LIMITATION DE RESPONSABILITÉ
Dans toute la mesure permise par le droit applicable dans chaque juridiction, les développeurs, les contributeurs et toute partie participant à la création ou à la distribution de Voyager ne sauraient être tenus responsables de dommages directs, indirects, accessoires, consécutifs, spéciaux, exemplaires ou punitifs de quelque nature que ce soit — y compris dommages corporels, décès ou pertes financières — découlant de l'utilisation ou de l'impossibilité d'utiliser l'application, même s'ils ont été avertis de l'éventualité de tels dommages. Lorsqu'une juridiction n'autorise pas tout ou partie de cette limitation, la responsabilité est limitée dans la plus faible mesure permise par la loi applicable.

🤝  GARANTIE D'INDEMNISATION
L'utilisateur s'engage à garantir et à mettre hors de cause les développeurs et les contributeurs contre toute réclamation, tout dommage, toute perte ou tout frais (y compris les frais de justice) découlant de son usage de l'application ou d'une violation des présentes conditions.

🔒  CONFIDENTIALITÉ ET SERVICES RÉSEAU
Voyager n'exploite aucun serveur propre, ne collecte aucune statistique d'usage et ne contient aucune forme de télémétrie, mais ce n'est pas une application hors ligne. Lorsque les fonctions concernées sont utilisées, des coordonnées ou des zones approximatives ainsi que l'adresse IP sont transmises directement à des tiers : fournisseurs de calcul d'itinéraire (départ, destination et étapes), OpenStreetMap/Nominatim/Overpass (recherche, géocodage inverse, points d'intérêt, zones réglementées, limitations et radars), Open-Meteo (coordonnées arrondies), serveurs de tuiles cartographiques et relais Nostr (geohash à l'échelle de la ville). Un signalement routier publie sur Nostr sa position exacte, son horodatage, son contenu et la clé publique de son auteur : il est pseudonyme et non anonyme. Les requêtes musicales ne sont adressées qu'au serveur configuré par l'utilisateur ; les identifiants de ce serveur sont stockés chiffrés sur l'appareil. La synthèse et la reconnaissance vocales fonctionnent entièrement sur l'appareil et n'envoient rien. Les appels et messages entrants sont affichés, éventuellement lus à voix haute, puis abandonnés : ils ne sont jamais enregistrés ni transmis.

🎧  CONTENUS ET LICENCES
Voyager lit uniquement des médias que l'utilisateur a déjà le droit de lire, depuis des serveurs qu'il exploite lui-même. L'application ne fournit aucun contenu propre ni aucun moyen d'en obtenir. La responsabilité de la licéité des contenus consultés incombe entièrement à l'utilisateur.

⚖️  DIVISIBILITÉ
Si une stipulation des présentes conditions est jugée inapplicable dans une juridiction donnée, elle sera limitée ou retranchée dans la mesure strictement nécessaire, toutes les autres stipulations conservant leur plein effet.

En utilisant Voyager, où que ce soit dans le monde, l'utilisateur confirme avoir lu, compris et accepté sans réserve chacune des conditions ci-dessus, et assume l'entière et complète responsabilité — ainsi que l'ensemble des risques — de l'usage de l'application et de toute conséquence en découlant.''';
