// Voyager's safety and liability notice, Romanian.
//
// Generated by hand from the English source in disclaimer_en.dart. When the
// English text changes in substance, every translation here has to change with
// it and VoyagerDisclaimer.acceptanceKey has to be bumped — a user who
// accepted an older set of obligations has not accepted the new ones.
library;

const String voyagerDisclaimerRo = '''
Voyager este un bord auto experimental, cu sursă deschisă și întreținut de comunitate. Combină navigația bazată pe datele OpenStreetMap și pe protocolul Nostr cu redarea media, informații meteo, sinteză vocală și funcții telefonice opționale. Prin descărcarea, instalarea sau utilizarea acestei aplicații, utilizatorul acceptă necondiționat toți termenii de mai jos, fără limitare teritorială:

🚗  SIGURANȚA RUTIERĂ ÎNAINTE DE TOATE
Conducătorul auto trebuie să privească permanent drumul și să respecte toate regulile de circulație și semnalizarea existentă, care prevalează întotdeauna asupra oricărei indicații a aplicației. Nu manipulați niciodată dispozitivul în timpul condusului; fixați-l înainte de plecare într-un suport omologat și vizibil și nu vă abateți niciodată atenția de la drum pentru a interacționa cu el cât timp vehiculul este în mișcare. În multe sisteme de drept, manipularea unui dispozitiv la volan constituie în sine o contravenție, indiferent de ceea ce afișează dispozitivul.

🎵  MULTIMEDIA ȘI TELEFONIE ÎN TIMPUL CONDUSULUI
Redarea muzicii, citirea mesajelor și gestionarea apelurilor sunt funcții de confort și sunt furnizate în aceleași condiții ca restul aplicației. Alegerea muzicii, parcurgerea unei biblioteci, citirea unui mesaj pe ecran sau purtarea unei conversații reprezintă sarcini cognitive care reduc performanța la volan. Configurați redarea înainte de plecare și folosiți comenzile fizice de pe volan în locul ecranului tactil ori de câte ori vehiculul este în mișcare. Acolo unde legea locală restricționează sau interzice folosirea telefonului la volan, acea lege prevalează, iar funcțiile corespunzătoare nu trebuie utilizate.

⚠️  ASUMAREA RISCULUI — LA NIVEL MONDIAL
Prin utilizarea aplicației Voyager, în orice țară și sub orice sistem juridic, utilizatorul își asumă cu bună știință și în mod voluntar TOATE riscurile legate de utilizarea acesteia, inclusiv, dar fără a se limita la: accidente rutiere, vătămări corporale, deces, daune materiale, daune aduse vehiculului, amenzi, sancțiuni administrative, ridicarea vehiculului, confiscarea acestuia, răspundere penală sau orice altă consecință care decurge direct ori indirect din încrederea acordată aplicației. Utilizatorul poartă singur întreaga răspundere pentru fiecare decizie de conducere și de navigație.

🚫  FĂRĂ GARANȚII
Voyager este furnizat strict "CA ATARE" și "ÎN LIMITA DISPONIBILITĂȚII", fără nicio garanție de niciun fel, expresă, implicită sau legală — inclusiv, fără limitare, garanții privind exactitatea, exhaustivitatea, fiabilitatea, disponibilitatea, vandabilitatea, potrivirea pentru un anumit scop și neîncălcarea drepturilor terților. Datele cartografice, traseele, limitele de viteză, camerele de viteză și informațiile privind zonele cu trafic restricționat provin din surse deschise, întreținute de comunitate (OpenStreetMap, Overpass API), care pot fi incomplete, depășite sau inexacte pentru orice țară, regiune sau localitate, în orice moment și fără preaviz. Utilizatorul este singurul răspunzător pentru verificarea independentă, înainte și în timpul călătoriei, a legalității și accesibilității oricărui traseu sugerat în raport cu semnalizarea și reglementările locale oficiale.

📍  PRECIZIE ȘI GPS
Poziționarea GPS poate fi imprecisă sau indisponibilă. Toate indicațiile, distanțele și alertele sunt furnizate exclusiv cu titlu orientativ și nu trebuie niciodată să constituie unicul temei al unei decizii de conducere.

🛡️  LIMITAREA RĂSPUNDERII
În măsura maximă permisă de legislația aplicabilă în orice jurisdicție, dezvoltatorii, colaboratorii și orice parte implicată în crearea sau distribuirea aplicației Voyager nu răspund pentru daune directe, indirecte, incidentale, subsecvente, speciale, exemplare sau punitive de orice natură — inclusiv vătămări corporale, deces sau pierderi financiare — decurgând din utilizarea sau imposibilitatea de a utiliza aplicația, chiar dacă au fost avertizați cu privire la posibilitatea unor asemenea daune. Acolo unde o jurisdicție nu permite, integral sau parțial, această limitare, răspunderea este limitată la cea mai mică măsură permisă de legea respectivă.

🤝  DESPĂGUBIRE
Utilizatorul se obligă să despăgubească și să exonereze dezvoltatorii și colaboratorii de orice pretenție, daună, pierdere sau cheltuială (inclusiv cheltuieli de judecată) care decurge din utilizarea aplicației de către acesta sau din încălcarea prezentelor condiții.

🔒  CONFIDENȚIALITATE ȘI SERVICII DE REȚEA
Voyager nu operează servere proprii, nu colectează statistici de utilizare și nu conține niciun fel de telemetrie, dar nu este o aplicație offline. Când sunt folosite funcțiile respective, coordonate sau zone aproximative și adresa IP sunt trimise direct unor terți: furnizori de trasee (punct de plecare, destinație și puncte intermediare), OpenStreetMap/Nominatim/Overpass (căutare, geocodare inversă, puncte de interes, zone restricționate, limite și camere), Open-Meteo (coordonate rotunjite), servere de dale cartografice și relee Nostr (geohash la nivel de oraș). O raportare de trafic publică pe Nostr poziția exactă, ora, conținutul și cheia publică, fiind pseudonimă, nu anonimă. Cererile de muzică ajung exclusiv la serverul configurat de utilizator; datele de autentificare pentru acesta sunt stocate criptat pe dispozitiv. Sinteza și recunoașterea vocală rulează integral pe dispozitiv și nu trimit nimic. Apelurile și mesajele primite sunt afișate și, opțional, citite cu voce tare, apoi sunt eliminate: nu sunt niciodată salvate și niciodată transmise.

🎧  CONȚINUT ȘI LICENȚE
Voyager redă exclusiv conținut pe care utilizatorul are deja dreptul să îl redea, de pe servere pe care le administrează el însuși. Aplicația nu oferă conținut propriu și niciun mijloc de a-l obține. Răspunderea pentru legalitatea conținutului accesat revine în întregime utilizatorului.

⚖️  CLAUZĂ DE SALVGARDARE
Dacă vreo prevedere din acești termeni este considerată inaplicabilă într-o anumită jurisdicție, aceasta va fi limitată sau eliminată în măsura minimă necesară, iar toate celelalte prevederi rămân pe deplin în vigoare.

Prin utilizarea aplicației Voyager, oriunde în lume, utilizatorul confirmă că a citit, a înțeles și a acceptat necondiționat fiecare dintre termenii de mai sus și își asumă răspunderea deplină și integrală — precum și întregul risc — pentru utilizarea aplicației și pentru orice consecință care decurge din aceasta.''';
